export const COUNTRIES = [
  { code: "DE", name: "Alemania",       nameEn: "Germany",      flagEmoji: "🇩🇪", yearJoined: 2002 },
  { code: "AT", name: "Austria",        nameEn: "Austria",       flagEmoji: "🇦🇹", yearJoined: 2002 },
  { code: "BE", name: "Bélgica",        nameEn: "Belgium",       flagEmoji: "🇧🇪", yearJoined: 2002 },
  { code: "ES", name: "España",         nameEn: "Spain",         flagEmoji: "🇪🇸", yearJoined: 2002 },
  { code: "FI", name: "Finlandia",      nameEn: "Finland",       flagEmoji: "🇫🇮", yearJoined: 2002 },
  { code: "FR", name: "Francia",        nameEn: "France",        flagEmoji: "🇫🇷", yearJoined: 2002 },
  { code: "GR", name: "Grecia",         nameEn: "Greece",        flagEmoji: "🇬🇷", yearJoined: 2002 },
  { code: "IE", name: "Irlanda",        nameEn: "Ireland",       flagEmoji: "🇮🇪", yearJoined: 2002 },
  { code: "IT", name: "Italia",         nameEn: "Italy",         flagEmoji: "🇮🇹", yearJoined: 2002 },
  { code: "LU", name: "Luxemburgo",     nameEn: "Luxembourg",    flagEmoji: "🇱🇺", yearJoined: 2002 },
  { code: "MC", name: "Mónaco",         nameEn: "Monaco",        flagEmoji: "🇲🇨", yearJoined: 2002 },
  { code: "NL", name: "Países Bajos",   nameEn: "Netherlands",   flagEmoji: "🇳🇱", yearJoined: 2002 },
  { code: "PT", name: "Portugal",       nameEn: "Portugal",      flagEmoji: "🇵🇹", yearJoined: 2002 },
  { code: "SM", name: "San Marino",     nameEn: "San Marino",    flagEmoji: "🇸🇲", yearJoined: 2002 },
  { code: "VA", name: "Vaticano",       nameEn: "Vatican City",  flagEmoji: "🇻🇦", yearJoined: 2002 },
  { code: "SI", name: "Eslovenia",      nameEn: "Slovenia",      flagEmoji: "🇸🇮", yearJoined: 2007 },
  { code: "CY", name: "Chipre",         nameEn: "Cyprus",        flagEmoji: "🇨🇾", yearJoined: 2008 },
  { code: "MT", name: "Malta",          nameEn: "Malta",         flagEmoji: "🇲🇹", yearJoined: 2008 },
  { code: "SK", name: "Eslovaquia",     nameEn: "Slovakia",      flagEmoji: "🇸🇰", yearJoined: 2009 },
  { code: "EE", name: "Estonia",        nameEn: "Estonia",       flagEmoji: "🇪🇪", yearJoined: 2011 },
  { code: "AD", name: "Andorra",        nameEn: "Andorra",       flagEmoji: "🇦🇩", yearJoined: 2014 },
  { code: "LV", name: "Letonia",        nameEn: "Latvia",        flagEmoji: "🇱🇻", yearJoined: 2014 },
  { code: "LT", name: "Lituania",       nameEn: "Lithuania",     flagEmoji: "🇱🇹", yearJoined: 2015 },
  { code: "HR", name: "Croacia",        nameEn: "Croatia",       flagEmoji: "🇭🇷", yearJoined: 2023 },
  { code: "BG", name: "Bulgaria",       nameEn: "Bulgaria",      flagEmoji: "🇧🇬", yearJoined: 2026 },
];

export const DENOMINATIONS = [0.01, 0.02, 0.05, 0.10, 0.20, 0.50, 1.00, 2.00];
