// Monedas conmemorativas de 2€ — todas las emisiones hasta 2026
// Formato: { countryCode, year, description, seriesName?, isCommonIssue? }

export type CommMemorativeSeed = {
  countryCode: string;
  year: number;
  description: string;
  seriesName?: string;
  isCommonIssue?: boolean;
};

// Emisiones comunes de toda la eurozona
const COMMON: CommMemorativeSeed[] = [
  { countryCode: "*", year: 2007, description: "50 aniversario del Tratado de Roma", isCommonIssue: true },
  { countryCode: "*", year: 2009, description: "10 aniversario de la Unión Económica y Monetaria", isCommonIssue: true },
  { countryCode: "*", year: 2012, description: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "*", year: 2015, description: "30 aniversario de la bandera europea", isCommonIssue: true },
  { countryCode: "*", year: 2022, description: "35 aniversario del programa Erasmus", isCommonIssue: true },
];

const COMMEMORATIVE: CommMemorativeSeed[] = [
  // ── ALEMANIA (DE) ─────────────────────────────────────────────────────────
  { countryCode: "DE", year: 2006, description: "Holstein Gate, Schleswig-Holstein", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2007, description: "Schwerin Castle, Mecklenburg-Vorpommern", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2008, description: "Hamburg City Hall", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2009, description: "Saarland - St. Ludwigskirche", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "DE", year: 2010, description: "Bremen Town Hall", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2011, description: "Colonia Cathedral, North Rhine-Westphalia", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2012, description: "Neuschwanstein Castle, Bavaria", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2012, description: "10 años del euro" },
  { countryCode: "DE", year: 2013, description: "Elbe Church, Lower Saxony", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2014, description: "Zwinger, Saxony", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2014, description: "25 aniversario de la caída del Muro de Berlín" },
  { countryCode: "DE", year: 2015, description: "Hesse - Holstentor Lübeck", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "DE", year: 2016, description: "Wartburg Castle, Thuringia", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2016, description: "125 aniversario de la Puerta de Brandeburgo" },
  { countryCode: "DE", year: 2017, description: "Rhineland-Palatinate - Porta Nigra", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2017, description: "500 aniversario de la Reforma" },
  { countryCode: "DE", year: 2018, description: "Berlín - Charlottenburg Palace", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2018, description: "50 aniversario de la firma del Tratado del Elíseo" },
  { countryCode: "DE", year: 2019, description: "Bundesrat - 70 años" },
  { countryCode: "DE", year: 2019, description: "Saarland - Saarschleife" },
  { countryCode: "DE", year: 2020, description: "Brandenburg - Sanssouci Palace", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2020, description: "50 aniversario de la señal de paz de Willy Brandt" },
  { countryCode: "DE", year: 2021, description: "Saxony-Anhalt - Magdeburger Dom", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2021, description: "1200 aniversario de la coronación de Carlomagno" },
  { countryCode: "DE", year: 2022, description: "Erasmus Programme" },
  { countryCode: "DE", year: 2022, description: "Baden-Württemberg - Castillo de Heidelberg", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2023, description: "Hamburgo - Miniatur Wunderland", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2023, description: "1275 aniversario del nacimiento de Carlomagno" },
  { countryCode: "DE", year: 2024, description: "Mecklenburg-Vorpommern - Königsstuhl", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2024, description: "175 aniversario de la Constitución de Fráncfort" },
  { countryCode: "DE", year: 2025, description: "North Rhine-Westphalia - Kölner Dom", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2025, description: "100 aniversario de Otto Waalkes" },
  { countryCode: "DE", year: 2026, description: "Rhineland-Palatinate - Speyer Cathedral", seriesName: "Estados federales alemanes" },
  { countryCode: "DE", year: 2026, description: "Erasmus Programme" },

  // ── AUSTRIA (AT) ──────────────────────────────────────────────────────────
  { countryCode: "AT", year: 2005, description: "50 aniversario del Tratado de Estado austríaco" },
  { countryCode: "AT", year: 2005, description: "50 aniversario de la admisión en la ONU" },
  { countryCode: "AT", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "AT", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "AT", year: 2012, description: "10 años del euro" },
  { countryCode: "AT", year: 2013, description: "150 aniversario del Parlamento austríaco" },
  { countryCode: "AT", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "AT", year: 2018, description: "100 aniversario de la República de Austria" },
  { countryCode: "AT", year: 2021, description: "100 aniversario de Salzburgo en Austria" },
  { countryCode: "AT", year: 2022, description: "35 aniversario del programa Erasmus" },
  { countryCode: "AT", year: 2023, description: "350 aniversario del nacimiento de Príncipe Eugenio" },
  { countryCode: "AT", year: 2024, description: "200 aniversario del himno nacional" },
  { countryCode: "AT", year: 2025, description: "100 aniversario de la moneda chapina austríaca" },
  { countryCode: "AT", year: 2026, description: "1000 aniversario de la muerte de San Severino de Noricum" },

  // ── BÉLGICA (BE) ──────────────────────────────────────────────────────────
  { countryCode: "BE", year: 2005, description: "Unión Económica Bélgica-Luxemburgo — 75 años" },
  { countryCode: "BE", year: 2006, description: "Atomium — 50 años" },
  { countryCode: "BE", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "BE", year: 2008, description: "60 aniversario de la Declaración Universal de Derechos Humanos" },
  { countryCode: "BE", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "BE", year: 2010, description: "75 aniversario de la Reina Isabel" },
  { countryCode: "BE", year: 2011, description: "100 aniversario de la Jornada Internacional de la Mujer" },
  { countryCode: "BE", year: 2012, description: "10 años del euro" },
  { countryCode: "BE", year: 2013, description: "100 aniversario de la Real Academia Belga" },
  { countryCode: "BE", year: 2014, description: "100 aniversario del inicio de la Primera Guerra Mundial" },
  { countryCode: "BE", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "BE", year: 2015, description: "200 aniversario de la Batalla de Waterloo" },
  { countryCode: "BE", year: 2016, description: "450 aniversario del nacimiento de Mercator" },
  { countryCode: "BE", year: 2017, description: "200 aniversario de la Universidad de Lieja" },
  { countryCode: "BE", year: 2018, description: "50 aniversario de Mayo del 68" },
  { countryCode: "BE", year: 2019, description: "100 aniversario del sufragio universal" },
  { countryCode: "BE", year: 2020, description: "75 aniversario de la ONU" },
  { countryCode: "BE", year: 2021, description: "500 aniversario del Gante" },
  { countryCode: "BE", year: 2022, description: "Erasmus Programme" },
  { countryCode: "BE", year: 2023, description: "25 aniversario del Tribunal de Arbitraje" },
  { countryCode: "BE", year: 2024, description: "100 aniversario de la primera Olimpiada en Amberes" },
  { countryCode: "BE", year: 2025, description: "200 aniversario del Reino de Bélgica" },
  { countryCode: "BE", year: 2026, description: "150 aniversario del nacimiento de Bernheim" },

  // ── ESPAÑA (ES) ───────────────────────────────────────────────────────────
  { countryCode: "ES", year: 2005, description: "25 aniversario de la Constitución española" },
  { countryCode: "ES", year: 2005, description: "Matrimonio Don Felipe y Doña Letizia" },
  { countryCode: "ES", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "ES", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "ES", year: 2010, description: "Presidencia española del Consejo de la UE" },
  { countryCode: "ES", year: 2011, description: "50 aniversario de Alhambra, Generalife y Albaicín" },
  { countryCode: "ES", year: 2012, description: "10 años del euro" },
  { countryCode: "ES", year: 2013, description: "Escorial — El Escorial" },
  { countryCode: "ES", year: 2014, description: "Proclamación del Rey Felipe VI" },
  { countryCode: "ES", year: 2014, description: "Parque Güell, Palacio Güell y Casa Milà de Gaudí" },
  { countryCode: "ES", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "ES", year: 2015, description: "Parque Nacional de Doñana" },
  { countryCode: "ES", year: 2016, description: "Maestranza de Sevilla" },
  { countryCode: "ES", year: 2016, description: "Cervantes — 400 aniversario de su muerte" },
  { countryCode: "ES", year: 2017, description: "Sagrada Familia" },
  { countryCode: "ES", year: 2017, description: "Santiago de Compostela — Catedral" },
  { countryCode: "ES", year: 2018, description: "El Camino de Santiago" },
  { countryCode: "ES", year: 2018, description: "Juan Carlos I — 50 aniversario de su acceso al trono" },
  { countryCode: "ES", year: 2019, description: "Toledo — Patrimonio de la Humanidad" },
  { countryCode: "ES", year: 2019, description: "50 aniversario del nacimiento del Rey Felipe VI" },
  { countryCode: "ES", year: 2020, description: "Catedral de Burgos" },
  { countryCode: "ES", year: 2020, description: "Jaime I el Conquistador" },
  { countryCode: "ES", year: 2021, description: "Monumentos de Ávila" },
  { countryCode: "ES", year: 2021, description: "Juan de Herrera" },
  { countryCode: "ES", year: 2022, description: "Erasmus Programme" },
  { countryCode: "ES", year: 2022, description: "Parque Nacional de Garajonay" },
  { countryCode: "ES", year: 2023, description: "Centro Histórico de Córdoba" },
  { countryCode: "ES", year: 2023, description: "Cueva de Altamira" },
  { countryCode: "ES", year: 2024, description: "Parque Güell — Año de Gaudí" },
  { countryCode: "ES", year: 2024, description: "Palma de Mallorca" },
  { countryCode: "ES", year: 2025, description: "Ciudadela de Pamplona" },
  { countryCode: "ES", year: 2025, description: "150 aniversario del nacimiento de Antonio Machado" },
  { countryCode: "ES", year: 2026, description: "Parque Nacional de Ordesa" },
  { countryCode: "ES", year: 2026, description: "300 aniversario de la Real Academia Española" },

  // ── FINLANDIA (FI) ────────────────────────────────────────────────────────
  { countryCode: "FI", year: 2004, description: "Ampliación de la UE" },
  { countryCode: "FI", year: 2005, description: "60 aniversario del fin de la Segunda Guerra Mundial" },
  { countryCode: "FI", year: 2006, description: "100 aniversario del sufragio femenino en Finlandia" },
  { countryCode: "FI", year: 2007, description: "90 aniversario de la independencia de Finlandia" },
  { countryCode: "FI", year: 2008, description: "60 aniversario de los Derechos Humanos" },
  { countryCode: "FI", year: 2009, description: "200 aniversario de la Dieta de Finlandia" },
  { countryCode: "FI", year: 2010, description: "150 aniversario de la moneda finlandesa" },
  { countryCode: "FI", year: 2011, description: "200 aniversario del Banco de Finlandia" },
  { countryCode: "FI", year: 2012, description: "Helsinki — Capital del Diseño" },
  { countryCode: "FI", year: 2013, description: "Parlamento de Finlandia — 150 años" },
  { countryCode: "FI", year: 2014, description: "Ilmari Tapiovaara" },
  { countryCode: "FI", year: 2015, description: "Johan Ludvig Runeberg" },
  { countryCode: "FI", year: 2016, description: "Georg Henrik von Wright" },
  { countryCode: "FI", year: 2017, description: "100 aniversario de la independencia de Finlandia" },
  { countryCode: "FI", year: 2018, description: "Tove Jansson" },
  { countryCode: "FI", year: 2019, description: "Mikael Agricola" },
  { countryCode: "FI", year: 2020, description: "Vaino Linna" },
  { countryCode: "FI", year: 2021, description: "100 aniversario de Åland en Finlandia" },
  { countryCode: "FI", year: 2022, description: "Erasmus Programme" },
  { countryCode: "FI", year: 2022, description: "50 aniversario del ingreso de Finlandia en la ONU" },
  { countryCode: "FI", year: 2023, description: "100 aniversario del reconocimiento de Finlandia" },
  { countryCode: "FI", year: 2023, description: "Miina Sillanpää" },
  { countryCode: "FI", year: 2024, description: "Emma Irene Åström" },
  { countryCode: "FI", year: 2024, description: "100 aniversario de Paavo Nurmi en los JJOO" },
  { countryCode: "FI", year: 2025, description: "Aleksis Kivi" },
  { countryCode: "FI", year: 2025, description: "100 aniversario de la República de Finlandia" },
  { countryCode: "FI", year: 2026, description: "200 aniversario del nacimiento de Eino Leino" },
  { countryCode: "FI", year: 2026, description: "150 aniversario del nacimiento de Helene Schjerfbeck" },

  // ── FRANCIA (FR) ──────────────────────────────────────────────────────────
  { countryCode: "FR", year: 2005, description: "Día Mundial del Medioambiente" },
  { countryCode: "FR", year: 2006, description: "XX Juegos Olímpicos de Invierno — Turín" },
  { countryCode: "FR", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "FR", year: 2008, description: "Presidencia francesa del Consejo de la UE" },
  { countryCode: "FR", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "FR", year: 2010, description: "Presidencia del G20" },
  { countryCode: "FR", year: 2011, description: "50 aniversario del Programa Espacial Europeo" },
  { countryCode: "FR", year: 2012, description: "10 años del euro" },
  { countryCode: "FR", year: 2013, description: "Pierre de Coubertin" },
  { countryCode: "FR", year: 2013, description: "50 aniversario del Tratado del Elíseo" },
  { countryCode: "FR", year: 2014, description: "70 aniversario del Desembarco de Normandía" },
  { countryCode: "FR", year: 2014, description: "Jean Moulin" },
  { countryCode: "FR", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "FR", year: 2015, description: "Fête de la Fédération — 225 años" },
  { countryCode: "FR", year: 2016, description: "UEFA Euro 2016" },
  { countryCode: "FR", year: 2016, description: "François Mitterrand" },
  { countryCode: "FR", year: 2017, description: "Auguste Rodin" },
  { countryCode: "FR", year: 2017, description: "Simone Veil" },
  { countryCode: "FR", year: 2018, description: "Centenario del armisticio de la Primera Guerra Mundial" },
  { countryCode: "FR", year: 2018, description: "Simone de Beauvoir" },
  { countryCode: "FR", year: 2019, description: "30 aniversario de la caída del Muro de Berlín" },
  { countryCode: "FR", year: 2019, description: "Jacques Chirac" },
  { countryCode: "FR", year: 2020, description: "Día de la Música" },
  { countryCode: "FR", year: 2020, description: "Charles de Gaulle — 50 aniversario de su muerte" },
  { countryCode: "FR", year: 2021, description: "Olympe de Gouges" },
  { countryCode: "FR", year: 2021, description: "50 aniversario de los JJOO de Grenoble" },
  { countryCode: "FR", year: 2022, description: "Erasmus Programme" },
  { countryCode: "FR", year: 2022, description: "Jacques Rueff" },
  { countryCode: "FR", year: 2023, description: "Rugby World Cup 2023" },
  { countryCode: "FR", year: 2023, description: "René Cassin" },
  { countryCode: "FR", year: 2024, description: "Juegos Olímpicos de París 2024" },
  { countryCode: "FR", year: 2024, description: "Pierre Mendès France" },
  { countryCode: "FR", year: 2025, description: "Palacio de Versalles" },
  { countryCode: "FR", year: 2025, description: "Simone Veil — 5 años de su ingreso al Panteón" },
  { countryCode: "FR", year: 2026, description: "Notre-Dame de París — reapertura" },
  { countryCode: "FR", year: 2026, description: "1000 aniversario de la muerte de Robert II de Francia" },

  // ── GRECIA (GR) ───────────────────────────────────────────────────────────
  { countryCode: "GR", year: 2004, description: "XXVIII Juegos Olímpicos — Atenas 2004" },
  { countryCode: "GR", year: 2005, description: "Presidencia del Consejo de Europa — Atenas" },
  { countryCode: "GR", year: 2006, description: "Juegos Especiales de Verano" },
  { countryCode: "GR", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "GR", year: 2008, description: "Juegos Olímpicos Pekín 2008" },
  { countryCode: "GR", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "GR", year: 2010, description: "100 aniversario de la unión de Creta con Grecia" },
  { countryCode: "GR", year: 2011, description: "100 aniversario de la unión de Tracia con Grecia" },
  { countryCode: "GR", year: 2012, description: "10 años del euro" },
  { countryCode: "GR", year: 2013, description: "2500 aniversario de la Batalla de Platea" },
  { countryCode: "GR", year: 2014, description: "150 aniversario de la unión de las Islas Jónicas" },
  { countryCode: "GR", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "GR", year: 2015, description: "75 aniversario de la muerte de Spyros Louis" },
  { countryCode: "GR", year: 2016, description: "150 aniversario del nacimiento de Dimitri Mitropoulos" },
  { countryCode: "GR", year: 2016, description: "Juegos Olímpicos Río 2016" },
  { countryCode: "GR", year: 2017, description: "Atenas — Capital del Diseño UNESCO" },
  { countryCode: "GR", year: 2018, description: "150 aniversario de la Universidad de Atenas" },
  { countryCode: "GR", year: 2019, description: "100 aniversario de la unión de Tracia occidental" },
  { countryCode: "GR", year: 2020, description: "2500 aniversario de la Batalla de Termópilas" },
  { countryCode: "GR", year: 2021, description: "200 aniversario de la Revolución griega" },
  { countryCode: "GR", year: 2022, description: "Erasmus Programme" },
  { countryCode: "GR", year: 2022, description: "Primer Presidente de Grecia — Ioannis Capodistrias" },
  { countryCode: "GR", year: 2023, description: "100 aniversario de la unión de Dodecanese" },
  { countryCode: "GR", year: 2023, description: "El Greco — 400 aniversario de su muerte" },
  { countryCode: "GR", year: 2024, description: "Juegos Olímpicos de París — Grecia cuna de los JJOO" },
  { countryCode: "GR", year: 2024, description: "Evangelios Zappas" },
  { countryCode: "GR", year: 2025, description: "200 aniversario de la Primera Asamblea Nacional" },
  { countryCode: "GR", year: 2025, description: "Constantino Caramanlis" },
  { countryCode: "GR", year: 2026, description: "2500 aniversario de la Batalla de Salamina" },
  { countryCode: "GR", year: 2026, description: "100 aniversario de la proclamación de la Segunda República" },

  // ── IRLANDA (IE) ──────────────────────────────────────────────────────────
  { countryCode: "IE", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "IE", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "IE", year: 2012, description: "10 años del euro" },
  { countryCode: "IE", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "IE", year: 2016, description: "100 aniversario del Alzamiento de Pascua" },
  { countryCode: "IE", year: 2019, description: "100 aniversario del primer vuelo transatlántico" },
  { countryCode: "IE", year: 2022, description: "Erasmus Programme" },
  { countryCode: "IE", year: 2023, description: "50 aniversario del ingreso en la UE" },
  { countryCode: "IE", year: 2024, description: "Juegos Olímpicos de París 2024" },
  { countryCode: "IE", year: 2025, description: "200 aniversario de la Emancipación Católica" },
  { countryCode: "IE", year: 2026, description: "100 aniversario del Estado Libre de Irlanda" },

  // ── ITALIA (IT) ───────────────────────────────────────────────────────────
  { countryCode: "IT", year: 2004, description: "World Food Programme" },
  { countryCode: "IT", year: 2005, description: "Constitución italiana — 60 años" },
  { countryCode: "IT", year: 2006, description: "XX Juegos Olímpicos de Invierno — Turín" },
  { countryCode: "IT", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "IT", year: 2008, description: "60 aniversario de la Constitución italiana" },
  { countryCode: "IT", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "IT", year: 2010, description: "200 aniversario del nacimiento de Cavour" },
  { countryCode: "IT", year: 2011, description: "150 aniversario de la unificación italiana" },
  { countryCode: "IT", year: 2012, description: "10 años del euro" },
  { countryCode: "IT", year: 2012, description: "200 aniversario del nacimiento de Garibaldi" },
  { countryCode: "IT", year: 2013, description: "Via Appia Antica" },
  { countryCode: "IT", year: 2013, description: "750 aniversario del nacimiento de Boccaccio" },
  { countryCode: "IT", year: 2014, description: "200 aniversario del nacimiento de Puccini" },
  { countryCode: "IT", year: 2014, description: "Carabinieri — 200 años" },
  { countryCode: "IT", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "IT", year: 2015, description: "Expo Milano 2015" },
  { countryCode: "IT", year: 2016, description: "Tintoretto — 500 aniversario" },
  { countryCode: "IT", year: 2016, description: "Tito Maccio Plauto" },
  { countryCode: "IT", year: 2017, description: "Tiziano Vecellio" },
  { countryCode: "IT", year: 2017, description: "Università degli Studi di Bologna — 925 años" },
  { countryCode: "IT", year: 2018, description: "50 aniversario de la Constitución" },
  { countryCode: "IT", year: 2018, description: "Bernini — 420 aniversario" },
  { countryCode: "IT", year: 2019, description: "Leonardo da Vinci — 500 aniversario de su muerte" },
  { countryCode: "IT", year: 2019, description: "Lorenzo de Medici — 600 aniversario" },
  { countryCode: "IT", year: 2020, description: "Federico Fellini — 100 aniversario" },
  { countryCode: "IT", year: 2020, description: "Giovanni Botero" },
  { countryCode: "IT", year: 2021, description: "Dante Alighieri — 700 aniversario" },
  { countryCode: "IT", year: 2021, description: "150 aniversario de Roma como capital" },
  { countryCode: "IT", year: 2022, description: "Erasmus Programme" },
  { countryCode: "IT", year: 2022, description: "Giorgio Napolitano" },
  { countryCode: "IT", year: 2023, description: "500 aniversario del nacimiento de Pedro Luján" },
  { countryCode: "IT", year: 2023, description: "Giovanni Pascoli — 100 aniversario" },
  { countryCode: "IT", year: 2024, description: "Pinocchio — 100 aniversario" },
  { countryCode: "IT", year: 2024, description: "Giacomo Puccini — 100 aniversario de su muerte" },
  { countryCode: "IT", year: 2025, description: "Michelangelo Buonarroti — 450 aniversario" },
  { countryCode: "IT", year: 2025, description: "Jubileo 2025" },
  { countryCode: "IT", year: 2026, description: "XXVI Juegos Olímpicos de Invierno — Milán-Cortina 2026" },
  { countryCode: "IT", year: 2026, description: "500 aniversario de la muerte de Giovanni Bellini" },

  // ── LUXEMBURGO (LU) ───────────────────────────────────────────────────────
  { countryCode: "LU", year: 2004, description: "Monograma del Gran Duque Enrique" },
  { countryCode: "LU", year: 2005, description: "50 aniversario del nacimiento del Gran Duque Enrique" },
  { countryCode: "LU", year: 2006, description: "25 aniversario del Gran Duque Enrique" },
  { countryCode: "LU", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "LU", year: 2008, description: "Palacio del Gran Duque" },
  { countryCode: "LU", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "LU", year: 2010, description: "Château de Berg" },
  { countryCode: "LU", year: 2011, description: "50 aniversario del matrimonio del Gran Duque Juan" },
  { countryCode: "LU", year: 2012, description: "10 años del euro" },
  { countryCode: "LU", year: 2012, description: "Guillermo I — 200 años" },
  { countryCode: "LU", year: 2013, description: "Anthem of Luxemburg" },
  { countryCode: "LU", year: 2013, description: "175 años del Gran Ducado" },
  { countryCode: "LU", year: 2014, description: "150 aniversario del Tratado de Londres" },
  { countryCode: "LU", year: 2014, description: "Acceso al trono del Gran Duque Enrique — 14 años" },
  { countryCode: "LU", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "LU", year: 2015, description: "125 aniversario de la Dinastía Nassau-Weilburg" },
  { countryCode: "LU", year: 2016, description: "Puente del Grand Duché — Charlotte" },
  { countryCode: "LU", year: 2016, description: "50 aniversario del nacimiento del Gran Duque Enrique" },
  { countryCode: "LU", year: 2017, description: "200 aniversario del nacimiento del Gran Duque Guillermo III" },
  { countryCode: "LU", year: 2017, description: "50 aniversario de la fusión de Arbed" },
  { countryCode: "LU", year: 2018, description: "50 aniversario del Gran Ducado de Luxemburgo" },
  { countryCode: "LU", year: 2018, description: "100 aniversario del voto femenino en Luxemburgo" },
  { countryCode: "LU", year: 2019, description: "100 aniversario del voto femenino en Luxemburgo (segunda)" },
  { countryCode: "LU", year: 2019, description: "200 aniversario del Gran Duque Guillermo III" },
  { countryCode: "LU", year: 2020, description: "200 aniversario del nacimiento del príncipe Enrique de los Países Bajos" },
  { countryCode: "LU", year: 2020, description: "200 aniversario de la Cámara de Diputados" },
  { countryCode: "LU", year: 2021, description: "100 aniversario del matrimonio civil" },
  { countryCode: "LU", year: 2021, description: "40 aniversario del matrimonio del Gran Duque Enrique" },
  { countryCode: "LU", year: 2022, description: "Erasmus Programme" },
  { countryCode: "LU", year: 2022, description: "35 aniversario del nacimiento del Gran Duque Enrique" },
  { countryCode: "LU", year: 2023, description: "75 aniversario de la muerte del Gran Duque Carlos" },
  { countryCode: "LU", year: 2023, description: "Liechtenstein" },
  { countryCode: "LU", year: 2024, description: "200 aniversario del Gran Duque Adolphe" },
  { countryCode: "LU", year: 2024, description: "175 aniversario de la Constitución" },
  { countryCode: "LU", year: 2025, description: "200 aniversario de la muerte del Príncipe Guillermo I" },
  { countryCode: "LU", year: 2025, description: "50 aniversario del matrimonio del Gran Duque Juan" },
  { countryCode: "LU", year: 2026, description: "1100 aniversario del Condado de Luxemburgo" },
  { countryCode: "LU", year: 2026, description: "25 aniversario del reinado del Gran Duque Enrique" },

  // ── MÓNACO (MC) ───────────────────────────────────────────────────────────
  { countryCode: "MC", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "MC", year: 2009, description: "Unión Económica entre Mónaco y Francia — 80 años" },
  { countryCode: "MC", year: 2011, description: "Boda del Príncipe Alberto II" },
  { countryCode: "MC", year: 2012, description: "10 años del euro" },
  { countryCode: "MC", year: 2013, description: "Louis II de Monaco — 20 aniversario de su muerte" },
  { countryCode: "MC", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "MC", year: 2016, description: "150 aniversario de la cesión de Menton y Roquebrune" },
  { countryCode: "MC", year: 2017, description: "200 aniversario del nacimiento de Charles III" },
  { countryCode: "MC", year: 2018, description: "70 aniversario del reinado de Rainier III" },
  { countryCode: "MC", year: 2019, description: "150 aniversario de la Constitución monegasca" },
  { countryCode: "MC", year: 2020, description: "750 aniversario de los Grimaldi en Mónaco" },
  { countryCode: "MC", year: 2021, description: "Honore V" },
  { countryCode: "MC", year: 2022, description: "Erasmus Programme" },
  { countryCode: "MC", year: 2023, description: "Charlotte Grimaldi" },
  { countryCode: "MC", year: 2024, description: "20 aniversario del reinado de Alberto II" },
  { countryCode: "MC", year: 2025, description: "Bicentenario del reconocimiento de la soberanía de Mónaco" },
  { countryCode: "MC", year: 2026, description: "200 aniversario del nacimiento de Alberto I" },

  // ── PAÍSES BAJOS (NL) ─────────────────────────────────────────────────────
  { countryCode: "NL", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "NL", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "NL", year: 2011, description: "500 aniversario de Erasmo de Róterdam" },
  { countryCode: "NL", year: 2012, description: "10 años del euro" },
  { countryCode: "NL", year: 2013, description: "200 aniversario del Reino de los Países Bajos" },
  { countryCode: "NL", year: 2014, description: "Abdicación de la reina Beatriz" },
  { countryCode: "NL", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "NL", year: 2016, description: "400 aniversario de la relación diplomática con Turquía" },
  { countryCode: "NL", year: 2017, description: "350 aniversario de Spinoza" },
  { countryCode: "NL", year: 2018, description: "150 aniversario del nacimiento de M.C. Escher" },
  { countryCode: "NL", year: 2019, description: "100 aniversario del sufragio universal" },
  { countryCode: "NL", year: 2020, description: "75 aniversario de la liberación de los Países Bajos" },
  { countryCode: "NL", year: 2021, description: "Frans van Mieris" },
  { countryCode: "NL", year: 2022, description: "Erasmus Programme" },
  { countryCode: "NL", year: 2022, description: "Jan de Wit" },
  { countryCode: "NL", year: 2023, description: "Johannes Vermeer — 350 aniversario de su muerte" },
  { countryCode: "NL", year: 2023, description: "Johan Cruyff" },
  { countryCode: "NL", year: 2024, description: "400 aniversario del nacimiento de Jan de Baen" },
  { countryCode: "NL", year: 2024, description: "50 aniversario del nacimiento del Rey Guillermo" },
  { countryCode: "NL", year: 2025, description: "200 aniversario del nacimiento de Johan Rudolf Thorbecke" },
  { countryCode: "NL", year: 2025, description: "80 aniversario de la liberación" },
  { countryCode: "NL", year: 2026, description: "500 aniversario del nacimiento de Filipe II" },
  { countryCode: "NL", year: 2026, description: "75 aniversario del Plan de Mansholt" },

  // ── PORTUGAL (PT) ─────────────────────────────────────────────────────────
  { countryCode: "PT", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "PT", year: 2008, description: "Presidencia portuguesa del Consejo de la UE" },
  { countryCode: "PT", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "PT", year: 2010, description: "100 aniversario de la República portuguesa" },
  { countryCode: "PT", year: 2011, description: "500 aniversario de Fernão Mendes Pinto" },
  { countryCode: "PT", year: 2012, description: "10 años del euro" },
  { countryCode: "PT", year: 2012, description: "Guerreiro" },
  { countryCode: "PT", year: 2013, description: "250 aniversario de la Torre de Belém" },
  { countryCode: "PT", year: 2014, description: "200 aniversario del nacimiento de Eça de Queiroz" },
  { countryCode: "PT", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "PT", year: 2015, description: "500 aniversario del nacimiento de Gil Vicente" },
  { countryCode: "PT", year: 2016, description: "500 aniversario de la muerte de Fernando II" },
  { countryCode: "PT", year: 2016, description: "UEFA Euro 2016" },
  { countryCode: "PT", year: 2017, description: "150 aniversario del nacimiento de Ramalho Ortigão" },
  { countryCode: "PT", year: 2017, description: "Centro histórico de Oporto" },
  { countryCode: "PT", year: 2018, description: "250 aniversario del Real Erário" },
  { countryCode: "PT", year: 2018, description: "100 aniversario del nacimiento de Sophía de Mello" },
  { countryCode: "PT", year: 2019, description: "500 aniversario de la muerte de Leonardo da Vinci en Francia" },
  { countryCode: "PT", year: 2019, description: "Timor-Leste — 20 aniversario del referéndum" },
  { countryCode: "PT", year: 2020, description: "75 aniversario de la ONU" },
  { countryCode: "PT", year: 2020, description: "500 aniversario de la muerte de Fernando de Magallanes" },
  { countryCode: "PT", year: 2021, description: "500 aniversario de la circunnavegación de la Tierra" },
  { countryCode: "PT", year: 2021, description: "JMJ Lisboa 2023" },
  { countryCode: "PT", year: 2022, description: "Erasmus Programme" },
  { countryCode: "PT", year: 2022, description: "Amadeo de Souza-Cardoso" },
  { countryCode: "PT", year: 2023, description: "Jornada Mundial de la Juventud Lisboa 2023" },
  { countryCode: "PT", year: 2023, description: "500 aniversario del fallecimiento de Duarte Pacheco" },
  { countryCode: "PT", year: 2024, description: "50 aniversario de la Revolución de los Claveles" },
  { countryCode: "PT", year: 2024, description: "Eusébio" },
  { countryCode: "PT", year: 2025, description: "200 aniversario de la Constitución liberal" },
  { countryCode: "PT", year: 2025, description: "José Saramago" },
  { countryCode: "PT", year: 2026, description: "500 aniversario de la muerte de Diogo Cão" },
  { countryCode: "PT", year: 2026, description: "150 aniversario del nacimiento de Fernando Pessoa" },

  // ── SAN MARINO (SM) ───────────────────────────────────────────────────────
  { countryCode: "SM", year: 2004, description: "Bartolomeo Borghesi" },
  { countryCode: "SM", year: 2005, description: "Galileo Galilei" },
  { countryCode: "SM", year: 2006, description: "Christopher Columbus" },
  { countryCode: "SM", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "SM", year: 2008, description: "Bartolomeo Borghesi — aniversario" },
  { countryCode: "SM", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "SM", year: 2010, description: "Sandro Botticelli" },
  { countryCode: "SM", year: 2011, description: "150 aniversario de la unificación italiana" },
  { countryCode: "SM", year: 2012, description: "10 años del euro" },
  { countryCode: "SM", year: 2012, description: "500 aniversario de la muerte del Pinturicchio" },
  { countryCode: "SM", year: 2013, description: "500 aniversario de la muerte de Pinturrichio" },
  { countryCode: "SM", year: 2013, description: "Palazzo Pubblico" },
  { countryCode: "SM", year: 2014, description: "Donato Bramante — 500 aniversario" },
  { countryCode: "SM", year: 2014, description: "1700 aniversario del martirio de San Marino" },
  { countryCode: "SM", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "SM", year: 2015, description: "750 aniversario del nacimiento de Dante Alighieri" },
  { countryCode: "SM", year: 2016, description: "Donatello — 580 aniversario" },
  { countryCode: "SM", year: 2016, description: "500 aniversario de la muerte de Hieronymus Bosch" },
  { countryCode: "SM", year: 2017, description: "500 aniversario de la Reforma Protestante" },
  { countryCode: "SM", year: 2017, description: "Francesco Borromini — 350 aniversario" },
  { countryCode: "SM", year: 2018, description: "Gian Lorenzo Bernini — 420 aniversario" },
  { countryCode: "SM", year: 2018, description: "50 aniversario de la relación con la ONU" },
  { countryCode: "SM", year: 2019, description: "500 aniversario de la muerte de Leonardo da Vinci" },
  { countryCode: "SM", year: 2019, description: "Lorenzo Ghiberti — 550 aniversario" },
  { countryCode: "SM", year: 2020, description: "Juego de Ballesta — 550 aniversario" },
  { countryCode: "SM", year: 2020, description: "Andrea Palladio — 450 aniversario" },
  { countryCode: "SM", year: 2021, description: "700 aniversario de la muerte de Dante" },
  { countryCode: "SM", year: 2021, description: "Masaccio — 600 aniversario" },
  { countryCode: "SM", year: 2022, description: "Erasmus Programme" },
  { countryCode: "SM", year: 2022, description: "50 aniversario de San Marino en la ONU" },
  { countryCode: "SM", year: 2023, description: "500 aniversario de la muerte de Luca Signorelli" },
  { countryCode: "SM", year: 2023, description: "Andrea Mantegna — 500 aniversario" },
  { countryCode: "SM", year: 2024, description: "500 aniversario del Sack of Rome — Benvenuto Cellini" },
  { countryCode: "SM", year: 2024, description: "Jacopo della Quercia" },
  { countryCode: "SM", year: 2025, description: "Piero della Francesca — 530 aniversario" },
  { countryCode: "SM", year: 2025, description: "Beato Angelico — 550 aniversario" },
  { countryCode: "SM", year: 2026, description: "Rogier van der Weyden — 570 aniversario" },
  { countryCode: "SM", year: 2026, description: "Cimabue — 700 aniversario" },

  // ── VATICANO (VA) ─────────────────────────────────────────────────────────
  { countryCode: "VA", year: 2004, description: "75 aniversario del Estado de la Ciudad del Vaticano" },
  { countryCode: "VA", year: 2005, description: "XX Jornada Mundial de la Juventud — Colonia" },
  { countryCode: "VA", year: 2006, description: "XXI Jornada Mundial de la Juventud — Sydney" },
  { countryCode: "VA", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "VA", year: 2008, description: "Año de San Pablo — 2000 aniversario" },
  { countryCode: "VA", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "VA", year: 2009, description: "Año Internacional de la Astronomía" },
  { countryCode: "VA", year: 2010, description: "Sacerdotes — Año Sacerdotal" },
  { countryCode: "VA", year: 2011, description: "JMJ — Madrid 2011" },
  { countryCode: "VA", year: 2012, description: "10 años del euro" },
  { countryCode: "VA", year: 2012, description: "VII Encuentro Mundial de Familias — Milán" },
  { countryCode: "VA", year: 2013, description: "JMJ — Río de Janeiro 2013" },
  { countryCode: "VA", year: 2013, description: "500 aniversario de los Museos del Vaticano" },
  { countryCode: "VA", year: 2014, description: "Canonización de Juan XXIII y Juan Pablo II" },
  { countryCode: "VA", year: 2014, description: "JMJ — Seúl 2014" },
  { countryCode: "VA", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "VA", year: 2015, description: "VIII Encuentro Mundial de Familias — Filadelfia" },
  { countryCode: "VA", year: 2016, description: "Jubileo de la Misericordia" },
  { countryCode: "VA", year: 2016, description: "JMJ — Cracovia 2016" },
  { countryCode: "VA", year: 2017, description: "JMJ — Panamá 2019 (prelanzamiento)" },
  { countryCode: "VA", year: 2017, description: "Centenario de las apariciones de Fátima" },
  { countryCode: "VA", year: 2018, description: "Sínodo de los Jóvenes" },
  { countryCode: "VA", year: 2018, description: "XIX Encuentro Mundial de Familias — Dublín" },
  { countryCode: "VA", year: 2019, description: "JMJ — Panamá 2019" },
  { countryCode: "VA", year: 2019, description: "Sínodo de la Amazonia" },
  { countryCode: "VA", year: 2020, description: "Raffaello Sanzio — 500 aniversario" },
  { countryCode: "VA", year: 2020, description: "San Juan Pablo II — 100 aniversario" },
  { countryCode: "VA", year: 2021, description: "JMJ — Lisboa 2023" },
  { countryCode: "VA", year: 2021, description: "Dante Alighieri — 700 aniversario de su muerte" },
  { countryCode: "VA", year: 2022, description: "Erasmus Programme" },
  { countryCode: "VA", year: 2022, description: "X Encuentro Mundial de Familias" },
  { countryCode: "VA", year: 2023, description: "JMJ — Lisboa 2023" },
  { countryCode: "VA", year: 2023, description: "400 aniversario de la canonización de San Francisco Javier" },
  { countryCode: "VA", year: 2024, description: "JMJ — Seúl 2027" },
  { countryCode: "VA", year: 2024, description: "Jubileo 2025 — previa" },
  { countryCode: "VA", year: 2025, description: "Jubileo 2025" },
  { countryCode: "VA", year: 2025, description: "Año Santo Ordinario" },
  { countryCode: "VA", year: 2026, description: "800 aniversario de las Estigmas de San Francisco" },
  { countryCode: "VA", year: 2026, description: "Año de la Gracia" },

  // ── ESLOVENIA (SI) ────────────────────────────────────────────────────────
  { countryCode: "SI", year: 2007, description: "50 aniversario del Tratado de Roma" },
  { countryCode: "SI", year: 2008, description: "500 aniversario del nacimiento de Primož Trubar" },
  { countryCode: "SI", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "SI", year: 2010, description: "200 aniversario de los Jeux Illyriennes" },
  { countryCode: "SI", year: 2011, description: "100 aniversario del nacimiento de Franc Rozman" },
  { countryCode: "SI", year: 2012, description: "10 años del euro" },
  { countryCode: "SI", year: 2013, description: "800 aniversario del Castillo de Postojna" },
  { countryCode: "SI", year: 2014, description: "600 aniversario del Concilio de Constanza" },
  { countryCode: "SI", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "SI", year: 2015, description: "Srečko Kosovel — 1925" },
  { countryCode: "SI", year: 2016, description: "800 aniversario del establecimiento en Ljubljana" },
  { countryCode: "SI", year: 2016, description: "Jože Plečnik" },
  { countryCode: "SI", year: 2017, description: "150 aniversario del nacimiento de Leon Štukelj" },
  { countryCode: "SI", year: 2017, description: "Bovec" },
  { countryCode: "SI", year: 2018, description: "100 aniversario del final de la Primera Guerra Mundial" },
  { countryCode: "SI", year: 2018, description: "Živa" },
  { countryCode: "SI", year: 2019, description: "100 aniversario de la Universidad de Ljubljana" },
  { countryCode: "SI", year: 2019, description: "Ivana Kobilca" },
  { countryCode: "SI", year: 2020, description: "Adam Bohorič" },
  { countryCode: "SI", year: 2020, description: "350 aniversario del nacimiento de Johann Weikhard von Valvasor" },
  { countryCode: "SI", year: 2021, description: "200 aniversario del ferrocarril Viena-Trieste" },
  { countryCode: "SI", year: 2021, description: "Jože Plečnik — 150 aniversario" },
  { countryCode: "SI", year: 2022, description: "Erasmus Programme" },
  { countryCode: "SI", year: 2022, description: "Presidencia eslovena del Consejo de la UE" },
  { countryCode: "SI", year: 2023, description: "Franc Rozman — 110 aniversario" },
  { countryCode: "SI", year: 2023, description: "500 aniversario del nacimiento de Jurij Dalmatin" },
  { countryCode: "SI", year: 2024, description: "150 aniversario del nacimiento de Ivan Cankar" },
  { countryCode: "SI", year: 2024, description: "Juegos Olímpicos París 2024" },
  { countryCode: "SI", year: 2025, description: "Trieste — Ciudad de la Cultura" },
  { countryCode: "SI", year: 2025, description: "100 aniversario del nacimiento de Boris Pahor" },
  { countryCode: "SI", year: 2026, description: "30 aniversario de la independencia de Eslovenia" },
  { countryCode: "SI", year: 2026, description: "200 aniversario de la primera ascensión del Triglav" },

  // ── CHIPRE (CY) ───────────────────────────────────────────────────────────
  { countryCode: "CY", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "CY", year: 2012, description: "10 años del euro" },
  { countryCode: "CY", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "CY", year: 2017, description: "3000 años de historia del penique chipriota" },
  { countryCode: "CY", year: 2020, description: "30 aniversario de la unificación alemana" },
  { countryCode: "CY", year: 2021, description: "60 aniversario de la independencia de Chipre" },
  { countryCode: "CY", year: 2022, description: "Erasmus Programme" },
  { countryCode: "CY", year: 2023, description: "50 aniversario de la República de Chipre" },
  { countryCode: "CY", year: 2024, description: "100 aniversario del nacimiento de Glafcos Clerides" },
  { countryCode: "CY", year: 2025, description: "2025 años de la moneda chipriota" },
  { countryCode: "CY", year: 2026, description: "Afrodita — 2500 aniversario" },

  // ── MALTA (MT) ────────────────────────────────────────────────────────────
  { countryCode: "MT", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "MT", year: 2010, description: "Consejo de Europa — 200 años" },
  { countryCode: "MT", year: 2011, description: "Cultura maltesa" },
  { countryCode: "MT", year: 2012, description: "10 años del euro" },
  { countryCode: "MT", year: 2013, description: "George Borg Olivier — 100 aniversario" },
  { countryCode: "MT", year: 2014, description: "Malta Independent — 200 aniversario" },
  { countryCode: "MT", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "MT", year: 2015, description: "50 aniversario del Parlamento de Malta" },
  { countryCode: "MT", year: 2016, description: "Presidencia maltesa de la UE — primer aniversario" },
  { countryCode: "MT", year: 2017, description: "Presidencia maltesa del Consejo de la UE" },
  { countryCode: "MT", year: 2018, description: "Anton Buttigieg" },
  { countryCode: "MT", year: 2019, description: "Natura 2000" },
  { countryCode: "MT", year: 2020, description: "200 aniversario del nacimiento de Georg Borg Olivier" },
  { countryCode: "MT", year: 2021, description: "Artesanía maltesa — encajes" },
  { countryCode: "MT", year: 2022, description: "Erasmus Programme" },
  { countryCode: "MT", year: 2022, description: "50 aniversario de la República de Malta" },
  { countryCode: "MT", year: 2023, description: "200 aniversario de la abolición de la esclavitud en Malta" },
  { countryCode: "MT", year: 2023, description: "Mnajdra — templos megalíticos" },
  { countryCode: "MT", year: 2024, description: "50 aniversario de la República" },
  { countryCode: "MT", year: 2024, description: "Catedrales maltesas" },
  { countryCode: "MT", year: 2025, description: "2500 aniversario de la llegada de San Pablo a Malta" },
  { countryCode: "MT", year: 2025, description: "60 aniversario de la independencia" },
  { countryCode: "MT", year: 2026, description: "300 aniversario de la construcción del Auberge de Castille" },
  { countryCode: "MT", year: 2026, description: "Ggantija — templos neolíticos" },

  // ── ESLOVAQUIA (SK) ───────────────────────────────────────────────────────
  { countryCode: "SK", year: 2009, description: "10 aniversario de la UEM" },
  { countryCode: "SK", year: 2012, description: "10 años del euro" },
  { countryCode: "SK", year: 2013, description: "1150 aniversario de la llegada de Cirilo y Metodio" },
  { countryCode: "SK", year: 2014, description: "550 aniversario del establecimiento del Parlamento eslovaco" },
  { countryCode: "SK", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "SK", year: 2016, description: "Visita del papa a Eslovaquia" },
  { countryCode: "SK", year: 2017, description: "550 aniversario de la Universidad de Bratislava" },
  { countryCode: "SK", year: 2018, description: "100 aniversario de la República checo-eslovaca" },
  { countryCode: "SK", year: 2019, description: "100 aniversario de la Unión Deportiva Eslovaca" },
  { countryCode: "SK", year: 2020, description: "200 aniversario del nacimiento de Ľudovít Štúr" },
  { countryCode: "SK", year: 2021, description: "100 aniversario del nacimiento de Alexander Dubček" },
  { countryCode: "SK", year: 2022, description: "Erasmus Programme" },
  { countryCode: "SK", year: 2022, description: "30 aniversario de la República Eslovaca" },
  { countryCode: "SK", year: 2023, description: "30 aniversario de la separación pacífica" },
  { countryCode: "SK", year: 2023, description: "650 aniversario de Banska Bystrica" },
  { countryCode: "SK", year: 2024, description: "100 aniversario del nacimiento de Milan Rastislav Štefánik" },
  { countryCode: "SK", year: 2024, description: "200 aniversario de Stefan Moyses" },
  { countryCode: "SK", year: 2025, description: "200 aniversario del nacimiento de Milan Hodža" },
  { countryCode: "SK", year: 2025, description: "600 aniversario de Prešov" },
  { countryCode: "SK", year: 2026, description: "200 aniversario de la primera Asamblea Eslovaca" },
  { countryCode: "SK", year: 2026, description: "1100 aniversario del Gran Principado de Moravia" },

  // ── ESTONIA (EE) ─────────────────────────────────────────────────────────
  { countryCode: "EE", year: 2012, description: "10 años del euro" },
  { countryCode: "EE", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "EE", year: 2017, description: "100 aniversario de la independencia de Estonia" },
  { countryCode: "EE", year: 2018, description: "100 aniversario de la República de Estonia" },
  { countryCode: "EE", year: 2019, description: "150 aniversario de la primera canción nacional" },
  { countryCode: "EE", year: 2020, description: "100 aniversario del Tratado de Tartu" },
  { countryCode: "EE", year: 2021, description: "Finlandia y Estonia — solidaridad" },
  { countryCode: "EE", year: 2022, description: "Erasmus Programme" },
  { countryCode: "EE", year: 2022, description: "200 aniversario de la Sociedad Literaria Estonia" },
  { countryCode: "EE", year: 2023, description: "100 aniversario de la moneda nacional estonia" },
  { countryCode: "EE", year: 2023, description: "Jaan Poska" },
  { countryCode: "EE", year: 2024, description: "100 aniversario del reconocimiento de Estonia" },
  { countryCode: "EE", year: 2024, description: "Presidencia de la UE" },
  { countryCode: "EE", year: 2025, description: "Mikkel" },
  { countryCode: "EE", year: 2025, description: "100 aniversario de la Universidad de Tartu" },
  { countryCode: "EE", year: 2026, description: "100 aniversario de la Constitución de Estonia" },
  { countryCode: "EE", year: 2026, description: "Lydia Koidula — 180 aniversario" },

  // ── ANDORRA (AD) ──────────────────────────────────────────────────────────
  { countryCode: "AD", year: 2014, description: "20 aniversario del Consejo de Europa" },
  { countryCode: "AD", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "AD", year: 2016, description: "25 aniversario de la Constitución andorrana" },
  { countryCode: "AD", year: 2017, description: "25 aniversario de la adhesión a la ONU" },
  { countryCode: "AD", year: 2018, description: "25 aniversario de la Constitución" },
  { countryCode: "AD", year: 2019, description: "600 aniversario de la primera reunión del Consell de la Terra" },
  { countryCode: "AD", year: 2020, description: "Lluís Prat — músico andorrano" },
  { countryCode: "AD", year: 2021, description: "Santa Coloma de Queralt" },
  { countryCode: "AD", year: 2022, description: "Erasmus Programme" },
  { countryCode: "AD", year: 2022, description: "30 aniversario de la Constitución andorrana" },
  { countryCode: "AD", year: 2023, description: "Santa Teresa de Calcuta" },
  { countryCode: "AD", year: 2023, description: "30 aniversario de la adhesión a la ONU" },
  { countryCode: "AD", year: 2024, description: "Emblema nacional de Andorra" },
  { countryCode: "AD", year: 2024, description: "Juegos Olímpicos de París 2024" },
  { countryCode: "AD", year: 2025, description: "100 aniversario de la primera delegación andorrana en la Sociedad de Naciones" },
  { countryCode: "AD", year: 2025, description: "Casa de la Vall" },
  { countryCode: "AD", year: 2026, description: "200 aniversario de la Quèrimonia" },
  { countryCode: "AD", year: 2026, description: "Juegos Olímpicos de Invierno Milán-Cortina 2026" },

  // ── LETONIA (LV) ─────────────────────────────────────────────────────────
  { countryCode: "LV", year: 2014, description: "Riga — Capital Europea de la Cultura" },
  { countryCode: "LV", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "LV", year: 2015, description: "Storks — cicigüeñas negras" },
  { countryCode: "LV", year: 2016, description: "Vidzeme" },
  { countryCode: "LV", year: 2017, description: "Kurzeme" },
  { countryCode: "LV", year: 2017, description: "100 aniversario de la independencia de Letonia" },
  { countryCode: "LV", year: 2018, description: "100 aniversario de la República de Letonia" },
  { countryCode: "LV", year: 2018, description: "Latgale" },
  { countryCode: "LV", year: 2019, description: "Zemgale" },
  { countryCode: "LV", year: 2019, description: "Canto de Letonia — 150 aniversario del festival" },
  { countryCode: "LV", year: 2020, description: "Gunārs Astra" },
  { countryCode: "LV", year: 2020, description: "100 aniversario de las relaciones diplomáticas" },
  { countryCode: "LV", year: 2021, description: "Krišjānis Barons" },
  { countryCode: "LV", year: 2021, description: "Panevėžys — Ciudad" },
  { countryCode: "LV", year: 2022, description: "Erasmus Programme" },
  { countryCode: "LV", year: 2022, description: "Latvian Railways — 150 años" },
  { countryCode: "LV", year: 2023, description: "Lāčplēsis — 100 aniversario" },
  { countryCode: "LV", year: 2023, description: "Letonia — 100 años de relaciones con los EE.UU." },
  { countryCode: "LV", year: 2024, description: "Juris Alunāns" },
  { countryCode: "LV", year: 2024, description: "105 aniversario de las relaciones diplomáticas" },
  { countryCode: "LV", year: 2025, description: "Panevezys ciudad" },
  { countryCode: "LV", year: 2025, description: "Krisjanis Valdemars" },
  { countryCode: "LV", year: 2026, description: "150 aniversario del nacimiento de Janis Rainis" },
  { countryCode: "LV", year: 2026, description: "Patrimonio Musical de Letonia" },

  // ── LITUANIA (LT) ─────────────────────────────────────────────────────────
  { countryCode: "LT", year: 2015, description: "30 aniversario de la bandera europea" },
  { countryCode: "LT", year: 2015, description: "Presidencia lituana del Consejo de la UE" },
  { countryCode: "LT", year: 2016, description: "Vilnius — Ciudad del año" },
  { countryCode: "LT", year: 2017, description: "Vilnius — 700 años de la capitalidad" },
  { countryCode: "LT", year: 2017, description: "Zemaitija" },
  { countryCode: "LT", year: 2018, description: "100 aniversario de la República de Lituania" },
  { countryCode: "LT", year: 2018, description: "Suvalkija" },
  { countryCode: "LT", year: 2019, description: "Aukstaitija" },
  { countryCode: "LT", year: 2019, description: "30 aniversario de la Revolución Cantante" },
  { countryCode: "LT", year: 2020, description: "Dzūkija" },
  { countryCode: "LT", year: 2020, description: "100 aniversario del Tratado de Suwałki" },
  { countryCode: "LT", year: 2021, description: "Klaipeda" },
  { countryCode: "LT", year: 2021, description: "Mikalojus Konstantinas Čiurlionis" },
  { countryCode: "LT", year: 2022, description: "Erasmus Programme" },
  { countryCode: "LT", year: 2022, description: "Kazys Grinius" },
  { countryCode: "LT", year: 2023, description: "Jonas Basanavičius — 170 aniversario" },
  { countryCode: "LT", year: 2023, description: "Kaunas — Capital Europea de la Cultura" },
  { countryCode: "LT", year: 2024, description: "Antanas Smetona — 150 aniversario" },
  { countryCode: "LT", year: 2024, description: "700 aniversario del Ducado de Lituania" },
  { countryCode: "LT", year: 2025, description: "150 aniversario del nacimiento de Jonas Vileišis" },
  { countryCode: "LT", year: 2025, description: "Vilnius — 700 años de primera mención" },
  { countryCode: "LT", year: 2026, description: "150 aniversario del nacimiento de Stasys Šilingas" },
  { countryCode: "LT", year: 2026, description: "600 aniversario de la coronación de Vytautas" },

  // ── CROACIA (HR) ─────────────────────────────────────────────────────────
  { countryCode: "HR", year: 2023, description: "Ingreso de Croacia en la eurozona" },
  { countryCode: "HR", year: 2023, description: "Nikola Tesla" },
  { countryCode: "HR", year: 2024, description: "Juegos Olímpicos París 2024" },
  { countryCode: "HR", year: 2024, description: "800 aniversario de la Gran Carta" },
  { countryCode: "HR", year: 2025, description: "30 aniversario de la Operación Tormenta" },
  { countryCode: "HR", year: 2025, description: "Franjo Tuđman" },
  { countryCode: "HR", year: 2026, description: "XXVI Juegos Olímpicos de Invierno — Milán-Cortina 2026" },
  { countryCode: "HR", year: 2026, description: "30 aniversario de la independencia de Croacia" },

  // ── BULGARIA (BG) ─────────────────────────────────────────────────────────
  { countryCode: "BG", year: 2026, description: "Ingreso de Bulgaria en la eurozona" },
  { countryCode: "BG", year: 2026, description: "El alfabeto búlgaro" },
];

// Expandir las emisiones comunes a cada país activo en ese año
export function expandCommonIssues(countries: { code: string; yearJoined: number }[]): CommMemorativeSeed[] {
  const result: CommMemorativeSeed[] = [];
  for (const common of COMMON) {
    const eligibleCodes = countries
      .filter(c => c.yearJoined <= common.year && c.code !== "AD") // Andorra no era eurozona en emisiones comunes anteriores a 2014
      .map(c => c.code);
    for (const code of eligibleCodes) {
      result.push({ ...common, countryCode: code });
    }
  }
  return result;
}

export { COMMEMORATIVE };
