// Monedas conmemorativas de 2€ — 575 emisiones hasta 2025
// Generado desde gilito.db (fuente: OpenNumismat + ECB)

export type CommemorativeSeed = {
  countryCode: string;
  year: number;
  description: string;
  seriesName?: string;
  isCommonIssue?: boolean;
};

export const COMMEMORATIVE: CommemorativeSeed[] = [
  // ── ANDORRA (AD) ─────────────────────────────────────────────
  { countryCode: "AD", year: 2014, description: "20 años en el Consejo de Europa" },
  { countryCode: "AD", year: 2015, description: "25 aniversario de la Firma del Acuerdo Aduanero con la Unión Europea" },
  { countryCode: "AD", year: 2015, description: "30.º aniversario de la Mayoría de Edad y Derechos Políticos para los Hombres y Mujeres que cumplen 18 años" },
  { countryCode: "AD", year: 2016, description: "150 años de la Nueva Reforma 1866" },
  { countryCode: "AD", year: 2016, description: "25 aniversario de la Radio y Televisión de Andorra" },
  { countryCode: "AD", year: 2017, description: "100 años del himno de Andorra, símbolo nacional pirenaico." },
  { countryCode: "AD", year: 2017, description: "Andorra, el país pirenaico, en su moneda conmemorativa." },
  { countryCode: "AD", year: 2018, description: "25.º aniversario de la Constitución Andorrana" },
  { countryCode: "AD", year: 2018, description: "70 años de la Declaración Universal de Derechos Humanos" },
  { countryCode: "AD", year: 2019, description: "Finales de la Copa del Mundo de Esquí 2019" },
  { countryCode: "AD", year: 2019, description: "600 años del Consejo de la Tierra" },
  { countryCode: "AD", year: 2020, description: "27ª Cumbre Iberoamericana en Andorra" },
  { countryCode: "AD", year: 2020, description: "50 años de sufragio femenino universal" },
  { countryCode: "AD", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "AD", year: 2022, description: "Leyenda de Carlomagno fundando Andorra en el 805" },
  { countryCode: "AD", year: 2022, description: "10 aniversario del acuerdo monetario con la UE" },
  { countryCode: "AD", year: 2023, description: "Festivales de hogueras del solsticio de verano en los Pirineos – UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "AD", year: 2023, description: "30.º aniversario de la entrada en las Naciones Unidas" },
  { countryCode: "AD", year: 2024, description: "Centenario del esquí en Andorra" },
  { countryCode: "AD", year: 2024, description: "Campeonatos del Mundo de Ciclismo de Montaña UCI 2024" },
  { countryCode: "AD", year: 2025, description: "Juegos de los Pequeños Estados de Europa – Andorra 2025" },
  { countryCode: "AD", year: 2025, description: "Quebrantahuesos – protección de fauna en peligro de extinción" },

  // ── AUSTRIA (AT) ─────────────────────────────────────────────
  { countryCode: "AT", year: 2005, description: "50 aniversario del Tratado de Estado de Austria" },
  { countryCode: "AT", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "AT", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "AT", year: 2012, description: "10 años del Euro: billetes y monedas en circulación.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "AT", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "AT", year: 2016, description: "200 Años del Banco Nacional de Austria" },
  { countryCode: "AT", year: 2018, description: "100 años de la República Austriaca" },
  { countryCode: "AT", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "AT", year: 2022, description: "35 años del programa Erasmus, intercambio educativo europeo.", seriesName: "35 años del programa Erasmus" },

  // ── BÉLGICA (BE) ─────────────────────────────────────────────
  { countryCode: "BE", year: 2005, description: "Unión Económica Bélgica-Luxemburgo" },
  { countryCode: "BE", year: 2006, description: "Atomium de Bruselas, icono de la Expo 58." },
  { countryCode: "BE", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "BE", year: 2008, description: "60 aniversario de la Declaración Universal de Derechos Humanos" },
  { countryCode: "BE", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "BE", year: 2009, description: "200.º aniversario del nacimiento de Louis Braille" },
  { countryCode: "BE", year: 2010, description: "Presidencia belga del Consejo de la UE 2010" },
  { countryCode: "BE", year: 2011, description: "100 aniversario del Día Internacional de la Mujer" },
  { countryCode: "BE", year: 2012, description: "10 años del Euro: billetes y monedas en circulación.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "BE", year: 2012, description: "75 aniversario del Concurso Reina Elisabeth" },
  { countryCode: "BE", year: 2013, description: "100 aniversario del Real Instituto Meteorológico" },
  { countryCode: "BE", year: 2014, description: "100 aniversario del estallido de la Primera Guerra Mundial" },
  { countryCode: "BE", year: 2014, description: "150 aniversario de la Cruz Roja Belga" },
  { countryCode: "BE", year: 2015, description: "Año Europeo para el Desarrollo, cooperación internacional." },
  { countryCode: "BE", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "BE", year: 2016, description: "Juegos Olímpicos, espíritu deportivo y unión." },
  { countryCode: "BE", year: 2016, description: "Día Internacional del Niño Desaparecido" },
  { countryCode: "BE", year: 2017, description: "200.º aniversario de la Universidad de Lieja" },
  { countryCode: "BE", year: 2017, description: "200 aniversario de la Universidad de Gante" },
  { countryCode: "BE", year: 2018, description: "50.º aniversario de los sucesos de mayo de 1968 en Bélgica" },
  { countryCode: "BE", year: 2018, description: "50.º aniversario del satélite ESRO 2B" },
  { countryCode: "BE", year: 2019, description: "450.º aniversario de la muerte de Pieter Bruegel el Viejo" },
  { countryCode: "BE", year: 2019, description: "25 aniversario del Instituto Monetario Europeo (IME)" },
  { countryCode: "BE", year: 2020, description: "Año Internacional de la Sanidad Vegetal 2020 (AISV 2020)" },
  { countryCode: "BE", year: 2020, description: "Jan van Eyck, maestro flamenco y pintor." },
  { countryCode: "BE", year: 2021, description: "100 Años de Unión Económica Bélgica-Luxemburgo (BLEU)" },
  { countryCode: "BE", year: 2021, description: "500 años de Carlos V, emperador del Sacro Imperio." },
  { countryCode: "BE", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "BE", year: 2022, description: "Trabajadores del sector sanitario en la pandemia de COVID-19" },
  { countryCode: "BE", year: 2023, description: "75 aniversario del sufragio femenino en Bélgica" },
  { countryCode: "BE", year: 2023, description: "Modernismo en Bélgica, arquitectura y arte." },
  { countryCode: "BE", year: 2024, description: "Lucha contra el cáncer, solidaridad y esperanza." },
  { countryCode: "BE", year: 2024, description: "Presidencia belga del Consejo de la UE" },
  { countryCode: "BE", year: 2025, description: "Lotería Nacional de Bélgica, suerte y tradición." },
  { countryCode: "BE", year: 2025, description: "Circuito de Spa-Francorchamps, leyenda del motor." },

  // ── CHIPRE (CY) ──────────────────────────────────────────────
  { countryCode: "CY", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "CY", year: 2012, description: "10 años del Euro: billetes y monedas en circulación.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "CY", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "CY", year: 2017, description: "Paphos 2017 – Capital Europea de la Cultura" },
  { countryCode: "CY", year: 2020, description: "30.º aniversario del Instituto de Neurología y Genética de Chipre" },
  { countryCode: "CY", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "CY", year: 2023, description: "60.º aniversario del Banco Central de Chipre" },
  { countryCode: "CY", year: 2024, description: "20 años desde la adhesión de Chipre a la Unión Europea" },

  // ── ALEMANIA (DE) ────────────────────────────────────────────
  { countryCode: "DE", year: 2006, description: "Schleswig-Holstein, castillo de Glücksburg.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2007, description: "Mecklemburgo-Pomerania Occidental", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "DE", year: 2008, description: "Hamburgo, Speicherstadt y Elbphilharmonie.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "DE", year: 2009, description: "Sarre, arquitectura industrial y patrimonio.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2010, description: "Bremen, Roland y ayuntamiento, Patrimonio UNESCO.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2011, description: "Renania del Norte-Westfalia, abadía de Maria Laach.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2012, description: "10 años del Euro: billetes y monedas en circulación.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "DE", year: 2012, description: "Baviera, castillo de Neuschwanstein.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2013, description: "50.º aniversario de la firma del Tratado de Amistad Franco-Alemán" },
  { countryCode: "DE", year: 2013, description: "Baden-Wurtemberg, palacio de Ludwigsburg.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2014, description: "Baja Sajonia, iglesia de San Miguel de Hildesheim.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2015, description: "Hesse, castillo de Marburgo.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2015, description: "25 años de la Unidad Alemana, reunificación histórica." },
  { countryCode: "DE", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "DE", year: 2016, description: "Sajonia, Zwinger de Dresde.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2017, description: "Renania-Palatinado, castillo de Eltz.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2018, description: "Berlín, Puerta de Brandeburgo.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2018, description: "100.º aniversario del nacimiento del gran estadista y canciller alemán Helmut Schmidt (1918-2015)" },
  { countryCode: "DE", year: 2019, description: "70 aniversario de la fundación del Bundesrat" },
  { countryCode: "DE", year: 2019, description: "30 aniversario de la caída del Muro de Berlín" },
  { countryCode: "DE", year: 2020, description: "Brandeburgo, palacio de Sanssouci.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2020, description: "50 aniversario del gesto de Willy Brandt en Varsovia (Kniefall von Warschau)" },
  { countryCode: "DE", year: 2021, description: "Sajonia-Anhalt, catedral de Naumburg.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "DE", year: 2022, description: "Turingia – Castillo de Wartburg", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2023, description: "Hamburgo, Elbphilharmonie, maravilla arquitectónica.", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2024, description: "Mecklemburgo-Pomerania Occidental – acantilados de tiza del Königsstuhl", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2024, description: "175.º aniversario de la Constitución de Fráncfort" },
  { countryCode: "DE", year: 2025, description: "Sarre – meandro del río Saarschleife", seriesName: "Estados federados de Alemania" },
  { countryCode: "DE", year: 2026, description: "Sajonia-Anhalt – Bauhaus Dessau", seriesName: "Estados federados de Alemania" },

  // ── ESTONIA (EE) ─────────────────────────────────────────────
  { countryCode: "EE", year: 2012, description: "10 años del Euro: billetes y monedas en circulación.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "EE", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "EE", year: 2016, description: "100.º aniversario del nacimiento del famoso gran maestro de ajedrez estonio Paul Keres" },
  { countryCode: "EE", year: 2017, description: "Independencia de Estonia, libertad y nación." },
  { countryCode: "EE", year: 2018, description: "100 aniversario de los Estados Bálticos" },
  { countryCode: "EE", year: 2018, description: "El centenario de la independencia de Estonia" },
  { countryCode: "EE", year: 2019, description: "150 aniversario del Festival de la Canción" },
  { countryCode: "EE", year: 2019, description: "Centenario de la Universidad de Tartu" },
  { countryCode: "EE", year: 2020, description: "El bicentenario del descubrimiento de la Antártida" },
  { countryCode: "EE", year: 2020, description: "Centenario del Tratado de Paz de Tartu" },
  { countryCode: "EE", year: 2021, description: "Pueblos Finougrios, cultura y diversidad." },
  { countryCode: "EE", year: 2021, description: "El Lobo – Animal Nacional de Estonia" },
  { countryCode: "EE", year: 2022, description: "150 aniversario de la fundación de la Sociedad de Literatos Estonios" },
  { countryCode: "EE", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "EE", year: 2022, description: "150 aniversario de la Sociedad de Literatos Estonios" },
  { countryCode: "EE", year: 2022, description: "Apoyo a Ucrania, solidaridad europea." },
  { countryCode: "EE", year: 2023, description: "Ave nacional de Estonia – golondrina común" },
  { countryCode: "EE", year: 2024, description: "Aciano – flor nacional de Estonia" },
  { countryCode: "EE", year: 2025, description: "500 aniversario de la primera publicación con palabras estonias" },

  // ── ESPAÑA (ES) ──────────────────────────────────────────────
  { countryCode: "ES", year: 2005, description: "400.º aniversario de la primera edición de \"Don Quijote de La Mancha\" de Miguel de Cervantes" },
  { countryCode: "ES", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "ES", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "ES", year: 2010, description: "Córdoba, Mezquita-Catedral, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2011, description: "Patio de los Leones de la Alhambra, Generalife y Albayzín en Granada", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2012, description: "10 años del Euro: billetes y monedas en circulación.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "ES", year: 2012, description: "Burgos, Catedral, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2013, description: "Monasterio de San Lorenzo de El Escorial", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2014, description: "Parque Güell, Obra de Antoni Gaudí", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2014, description: "Sucesión de Su Majestad el Rey Felipe VI al Trono" },
  { countryCode: "ES", year: 2015, description: "Cueva de Altamira, arte rupestre, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "ES", year: 2016, description: "Segovia: Acueducto romano, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2017, description: "Asturias: Iglesias prerrománicas, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2018, description: "Santiago: Catedral y Camino, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2018, description: "50.º aniversario del Rey Felipe VI" },
  { countryCode: "ES", year: 2019, description: "La ciudad vieja de Ávila y sus iglesias extramuros", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2020, description: "Aragón y la arquitectura mudéjar aragonesa", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2021, description: "Toledo: Ciudad histórica, Patrimonio UNESCO.", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "ES", year: 2022, description: "500.º aniversario de la primera circunnavegación de la Tierra (Elcano)" },
  { countryCode: "ES", year: 2022, description: "Parque Nacional de Garajonay – Patrimonio de la Humanidad de la UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2023, description: "Presidencia española del Consejo de la UE" },
  { countryCode: "ES", year: 2023, description: "Cáceres – Patrimonio de la Humanidad de la UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2024, description: "200 años de la Policía Nacional de España" },
  { countryCode: "ES", year: 2024, description: "Catedral, Alcázar y Archivo de Indias de Sevilla – UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2025, description: "Salamanca – Patrimonio de la Humanidad de la UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2026, description: "Monasterio de Poblet – Patrimonio de la Humanidad de la UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "ES", year: 2026, description: "Art. 49 – Derechos de inclusión y discapacidad" },

  // ── FINLANDIA (FI) ───────────────────────────────────────────
  { countryCode: "FI", year: 2004, description: "Ampliación de la Unión Europea a diez nuevos Estados miembros" },
  { countryCode: "FI", year: 2005, description: "60.º aniversario del establecimiento de las Naciones Unidas y 50.º aniversario de la membresía de Finlandia" },
  { countryCode: "FI", year: 2006, description: "100 años de sufragio universal e igual en Finlandia" },
  { countryCode: "FI", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "FI", year: 2007, description: "90.º aniversario de la declaración de independencia" },
  { countryCode: "FI", year: 2008, description: "60 aniversario de la Declaración Universal de Derechos Humanos" },
  { countryCode: "FI", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "FI", year: 2009, description: "200.º aniversario de la primera Dieta de Finlandia" },
  { countryCode: "FI", year: 2010, description: "Decreto Monetario de 1860 que otorga a Finlandia el derecho a emitir billetes y monedas" },
  { countryCode: "FI", year: 2011, description: "200 aniversario del Banco de Finlandia" },
  { countryCode: "FI", year: 2012, description: "Finlandia: 10 años del Euro, moneda y billete.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "FI", year: 2012, description: "Finlandia: 150 años de Helene Schjerfbeck." },
  { countryCode: "FI", year: 2013, description: "150 aniversario del Parlamento de 1863, cuando comenzaron las sesiones parlamentarias regulares en Finlandia" },
  { countryCode: "FI", year: 2013, description: "150 aniversario del nacimiento de Frans Emil Sillanpää" },
  { countryCode: "FI", year: 2014, description: "100.º aniversario de Tove Jansson" },
  { countryCode: "FI", year: 2014, description: "100 aniversario del nacimiento de la autora y artista Tove Jansson" },
  { countryCode: "FI", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "FI", year: 2015, description: "150 aniversario del nacimiento del compositor Jean Sibelius" },
  { countryCode: "FI", year: 2015, description: "150 aniversario del nacimiento del artista Akseli Gallen-Kallela" },
  { countryCode: "FI", year: 2016, description: "150 aniversario del nacimiento del artista Akseli Gallen-Kallela" },
  { countryCode: "FI", year: 2016, description: "100 aniversario del nacimiento del filósofo Georg Henrik von Wright" },
  { countryCode: "FI", year: 2017, description: "Finlandia Independiente 100 años" },
  { countryCode: "FI", year: 2017, description: "Finlandia: Belleza de la naturaleza." },
  { countryCode: "FI", year: 2018, description: "Paisaje nacional finlandés Koli" },
  { countryCode: "FI", year: 2018, description: "Finlandia: Tradición de la sauna." },
  { countryCode: "FI", year: 2019, description: "La Ley Constitucional de Finlandia" },
  { countryCode: "FI", year: 2020, description: "Universidades y sociedad – Universidad de Turku 100 años" },
  { countryCode: "FI", year: 2020, description: "Finlandia: 100 años de Väinö Linna." },
  { countryCode: "FI", year: 2021, description: "Periodismo y Comunicación Abierta en Apoyo a la Democracia Finlandesa" },
  { countryCode: "FI", year: 2021, description: "Finlandia: 100 años autonomía Åland." },
  { countryCode: "FI", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "FI", year: 2022, description: "Investigación climática – líquen de barba" },
  { countryCode: "FI", year: 2022, description: "100 años del Ballet Nacional de Finlandia" },
  { countryCode: "FI", year: 2023, description: "Primera Ley de Conservación de la Naturaleza de Finlandia" },
  { countryCode: "FI", year: 2023, description: "Servicios sociales y sanitarios" },
  { countryCode: "FI", year: 2024, description: "Arquitectura finlandesa – Gesellius, Lindgren y Saarinen" },
  { countryCode: "FI", year: 2024, description: "Finlandia: Elecciones y democracia." },
  { countryCode: "FI", year: 2025, description: "Visitas de Estado y diplomacia finlandesa" },
  { countryCode: "FI", year: 2025, description: "Atletismo Internacional Finlandia-Suecia – centenario" },

  // ── FRANCIA (FR) ─────────────────────────────────────────────
  { countryCode: "FR", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "FR", year: 2008, description: "Presidencia francesa del Consejo de la Unión Europea en el segundo semestre de 2008" },
  { countryCode: "FR", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "FR", year: 2010, description: "70 aniversario del llamamiento del 18 de junio" },
  { countryCode: "FR", year: 2011, description: "30 aniversario del Día de la Música (Fête de la musique)" },
  { countryCode: "FR", year: 2012, description: "Francia: 10 años del Euro, moneda y billete.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "FR", year: 2012, description: "100 aniversario del nacimiento del Abbé Pierre, conocido en Francia como protector de los Pobres" },
  { countryCode: "FR", year: 2013, description: "50.º aniversario de la firma del Tratado de Amistad Franco-Alemán" },
  { countryCode: "FR", year: 2013, description: "150.º Aniversario del nacimiento de Pierre de Coubertin" },
  { countryCode: "FR", year: 2014, description: "Francia: 70 años del Día D." },
  { countryCode: "FR", year: 2014, description: "Francia: Día Mundial del SIDA." },
  { countryCode: "FR", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "FR", year: 2015, description: "Europa construyendo paz y seguridad desde 1945" },
  { countryCode: "FR", year: 2015, description: "225 aniversario de la Fiesta de la Federación" },
  { countryCode: "FR", year: 2016, description: "Campeonato de Europa de la UEFA 2016" },
  { countryCode: "FR", year: 2016, description: "Francia: Homenaje a François Mitterrand." },
  { countryCode: "FR", year: 2017, description: "Francia: Centenario de Auguste Rodin." },
  { countryCode: "FR", year: 2017, description: "25.º aniversario del lazo rosa, símbolo de la lucha contra el cáncer de mama" },
  { countryCode: "FR", year: 2018, description: "Amapola del recuerdo (Bleuet de France)" },
  { countryCode: "FR", year: 2018, description: "Francia: Homenaje a Simone Veil." },
  { countryCode: "FR", year: 2019, description: "Francia: 60 años de Astérix." },
  { countryCode: "FR", year: 2019, description: "30 años de la caída del Muro de Berlín" },
  { countryCode: "FR", year: 2020, description: "Francia: Homenaje a Charles de Gaulle." },
  { countryCode: "FR", year: 2020, description: "Francia: Avances en investigación médica." },
  { countryCode: "FR", year: 2021, description: "Francia: 70 años UNICEF." },
  { countryCode: "FR", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "FR", year: 2022, description: "Juegos Olímpicos de París 2024 – cuenta atrás" },
  { countryCode: "FR", year: 2022, description: "90.º aniversario del nacimiento del Presidente Jacques Chirac" },
  { countryCode: "FR", year: 2023, description: "Copa Mundial de Rugby Francia 2023" },
  { countryCode: "FR", year: 2023, description: "Francia: París 2024 Juegos Olímpicos." },
  { countryCode: "FR", year: 2024, description: "Juegos Olímpicos de París 2024 – Torre Eiffel" },
  { countryCode: "FR", year: 2024, description: "Juegos Olímpicos de París 2024 – lucha y quimera de Notre-Dame" },
  { countryCode: "FR", year: 2025, description: "Francia: El Museo del Louvre." },

  // ── GRECIA (GR) ──────────────────────────────────────────────
  { countryCode: "GR", year: 2004, description: "Juegos Olímpicos de Atenas 2004" },
  { countryCode: "GR", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "GR", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "GR", year: 2010, description: "2.500 aniversario de la Batalla de Maratón" },
  { countryCode: "GR", year: 2011, description: "La organización de los Juegos Mundiales OLIMPIADAS ESPECIALES – ATENAS 2011" },
  { countryCode: "GR", year: 2012, description: "Grecia: 10 años del Euro, moneda y billete.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "GR", year: 2013, description: "2400 aniversario de la Academia Platónica" },
  { countryCode: "GR", year: 2013, description: "100 aniversario del acceso de Creta a Grecia" },
  { countryCode: "GR", year: 2014, description: "400 aniversario de la Muerte de Domenikos Theotokopoulos \"El Greco\"" },
  { countryCode: "GR", year: 2014, description: "150 aniversario de la unión de las Islas Jónicas a Grecia" },
  { countryCode: "GR", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "GR", year: 2015, description: "75 años in memoriam de Spyros Louis" },
  { countryCode: "GR", year: 2016, description: "120 años del nacimiento de Dimitri Mitropoulos" },
  { countryCode: "GR", year: 2016, description: "150 años desde el incendio del Monasterio de Arkadi" },
  { countryCode: "GR", year: 2017, description: "60 años in memoriam de Nikos Kazantzakis" },
  { countryCode: "GR", year: 2017, description: "Grecia: Sitio arqueológico de Filipos." },
  { countryCode: "GR", year: 2018, description: "Kostis Palamas – 75 años in memoriam" },
  { countryCode: "GR", year: 2018, description: "70 años desde la unión del Dodecaneso" },
  { countryCode: "GR", year: 2019, description: "Centenario del nacimiento de Manolis Andronicos" },
  { countryCode: "GR", year: 2019, description: "Andreas Kalvos — 150 años in memoriam" },
  { countryCode: "GR", year: 2020, description: "2500 años desde la Batalla de las Termópilas" },
  { countryCode: "GR", year: 2020, description: "100 años desde la unión de Tracia con Grecia" },
  { countryCode: "GR", year: 2021, description: "200 años de la Revolución Griega" },
  { countryCode: "GR", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "GR", year: 2022, description: "200 aniversario de la primera Constitución griega" },
  { countryCode: "GR", year: 2023, description: "100 años desde el nacimiento de Maria Callas" },
  { countryCode: "GR", year: 2023, description: "150 años desde el nacimiento de Constantin Carathéodory" },
  { countryCode: "GR", year: 2024, description: "50 años desde la restauración de la democracia en Grecia" },
  { countryCode: "GR", year: 2024, description: "150 años del nacimiento de Penelope Delta" },
  { countryCode: "GR", year: 2025, description: "200 años desde la muerte de Laskarina Bouboulina" },
  { countryCode: "GR", year: 2025, description: "100 años desde el nacimiento de Mikis Theodorakis" },

  // ── CROACIA (HR) ─────────────────────────────────────────────
  { countryCode: "HR", year: 2023, description: "Introducción del euro en Croacia" },
  { countryCode: "HR", year: 2024, description: "500 aniversario del legado literario de Marko Marulić" },
  { countryCode: "HR", year: 2024, description: "Fortaleza medieval del casco antiguo de Varaždin" },
  { countryCode: "HR", year: 2025, description: "1100 aniversario del Reino de Croacia y del Rey Tomislav" },
  { countryCode: "HR", year: 2025, description: "Anfiteatro romano de Pula – Serie de ciudades croatas" },

  // ── IRLANDA (IE) ─────────────────────────────────────────────
  { countryCode: "IE", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "IE", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "IE", year: 2012, description: "Irlanda: 10 años del Euro, moneda y billete.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "IE", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "IE", year: 2016, description: "100 años desde el Alzamiento de Pascua de 1916 en Irlanda" },
  { countryCode: "IE", year: 2019, description: "100 años desde el establecimiento del Dáil Éireann (Parlamento irlandés)" },
  { countryCode: "IE", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "IE", year: 2023, description: "50.º aniversario de la adhesión de Irlanda a la UE" },

  // ── ITALIA (IT) ──────────────────────────────────────────────
  { countryCode: "IT", year: 2004, description: "Cuarenta años del Programa Mundial de Alimentos" },
  { countryCode: "IT", year: 2005, description: "Primer aniversario de la firma de la Constitución Europea" },
  { countryCode: "IT", year: 2006, description: "XX Juegos Olímpicos de Invierno de Turín 2006" },
  { countryCode: "IT", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "IT", year: 2008, description: "60 aniversario de la Declaración Universal de Derechos Humanos" },
  { countryCode: "IT", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "IT", year: 2009, description: "200.º aniversario del nacimiento de Louis Braille" },
  { countryCode: "IT", year: 2010, description: "Bicentenario del nacimiento de Cavour" },
  { countryCode: "IT", year: 2011, description: "150 aniversario de la unificación de Italia" },
  { countryCode: "IT", year: 2012, description: "Italia: 10 años del Euro, moneda y billete.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "IT", year: 2012, description: "100.º aniversario de la muerte de Giovanni Pascoli" },
  { countryCode: "IT", year: 2013, description: "200 aniversario del nacimiento de Giuseppe Verdi" },
  { countryCode: "IT", year: 2013, description: "700.º aniversario del nacimiento de Giovanni Boccaccio" },
  { countryCode: "IT", year: 2014, description: "200 aniversario de los Carabinieri" },
  { countryCode: "IT", year: 2014, description: "450.º aniversario del Nacimiento de Galileo" },
  { countryCode: "IT", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "IT", year: 2015, description: "Italia: EXPO Milán 2015." },
  { countryCode: "IT", year: 2015, description: "750 aniversario del nacimiento de Dante Alighieri 1265-2015" },
  { countryCode: "IT", year: 2016, description: "550 aniversario de la muerte de Donatello" },
  { countryCode: "IT", year: 2016, description: "2200 aniversario de la muerte de Tito Maccio Plauto" },
  { countryCode: "IT", year: 2017, description: "400 Aniversario de la finalización de la Basílica de San Marcos de Venecia" },
  { countryCode: "IT", year: 2017, description: "Bimilenario de la muerte de Tito Livio" },
  { countryCode: "IT", year: 2018, description: "70.º Aniversario de la entrada en vigor de la Constitución Italiana" },
  { countryCode: "IT", year: 2018, description: "60.º aniversario de la creación del Ministerio de Salud italiano" },
  { countryCode: "IT", year: 2019, description: "500.º aniversario de la muerte de Leonardo da Vinci" },
  { countryCode: "IT", year: 2020, description: "80.º Aniversario de la Fundación del \"Corpo Nazionale dei Vigili del Fuoco\" (Cuerpo Nacional de Bomberos)" },
  { countryCode: "IT", year: 2020, description: "150 aniversario del nacimiento de Maria Montessori" },
  { countryCode: "IT", year: 2021, description: "150.º aniversario de la institución de Roma Capital de Italia" },
  { countryCode: "IT", year: 2021, description: "Italia: Profesionales de la salud." },
  { countryCode: "IT", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "IT", year: 2022, description: "30 aniversario de la muerte de los jueces Falcone y Borsellino" },
  { countryCode: "IT", year: 2022, description: "170 aniversario de la fundación de la Policía Nacional italiana" },
  { countryCode: "IT", year: 2023, description: "100.º aniversario de la Fuerza Aérea Italiana" },
  { countryCode: "IT", year: 2023, description: "150.º aniversario de la muerte de Alessandro Manzoni" },
  { countryCode: "IT", year: 2024, description: "250.º aniversario de la Guardia di Finanza" },
  { countryCode: "IT", year: 2024, description: "Rita Levi-Montalcini – Científica Premio Nobel" },
  { countryCode: "IT", year: 2025, description: "Jubileo 2025 – Puerta Santa de la Basílica de San Pedro" },
  { countryCode: "IT", year: 2025, description: "Vuelta al mundo de Amerigo Vespucci 2023-2025" },
  { countryCode: "IT", year: 2026, description: "Juegos Olímpicos de Invierno Milán-Cortina 2026" },

  // ── LITUANIA (LT) ────────────────────────────────────────────
  { countryCode: "LT", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "LT", year: 2015, description: "Lituania: La lengua lituana." },
  { countryCode: "LT", year: 2016, description: "Lituania: Patrimonio de la cultura báltica." },
  { countryCode: "LT", year: 2017, description: "Lituania: Vilna, capital histórica." },
  { countryCode: "LT", year: 2018, description: "100 aniversario de los Estados Bálticos" },
  { countryCode: "LT", year: 2018, description: "Celebración de Canto y Danza de Lituania" },
  { countryCode: "LT", year: 2019, description: "Lituania: Sutartinės, canto polifónico." },
  { countryCode: "LT", year: 2019, description: "Lituania: Región de Samogitia." },
  { countryCode: "LT", year: 2020, description: "Lituania: Región de Aukštaitija." },
  { countryCode: "LT", year: 2020, description: "Lituania: Kryžių Kalnas, Colina de las Cruces." },
  { countryCode: "LT", year: 2021, description: "Reserva de la Biosfera de Žuvintas" },
  { countryCode: "LT", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "LT", year: 2022, description: "Región etnográfica de Suvalkija" },
  { countryCode: "LT", year: 2022, description: "100 años de baloncesto en Lituania" },
  { countryCode: "LT", year: 2023, description: "Lituania: Solidaridad con Ucrania." },
  { countryCode: "LT", year: 2024, description: "Tradición lituana de jardines de paja – UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "LT", year: 2025, description: "Defensa – Lituania como un erizo" },
  { countryCode: "LT", year: 2025, description: "Regiones etnográficas lituanas – Lituania Menor" },

  // ── LUXEMBURGO (LU) ──────────────────────────────────────────
  { countryCode: "LU", year: 2004, description: "Luxemburgo: Gran Duque Enrique.", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2005, description: "Gran Duque Enrique y Gran Duque Adolfo", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2006, description: "25 cumpleaños del Gran Duque Guillermo, heredero al trono", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2007, description: "Luxemburgo: Palacio Gran Ducal.", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "LU", year: 2008, description: "Gran Duque Enrique y su residencia oficial ‘Château de Berg’", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "LU", year: 2009, description: "Gran Duque Enrique y Gran Duquesa Carlota", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2010, description: "Luxemburgo: Escudo Gran Duque.", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2011, description: "50 aniversario del nombramiento por la Gran Duquesa Carlota de su hijo Juan como \"lugarteniente-representante\"", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2012, description: "Gran Duque Enrique y el Gran Duque Guillermo IV", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2012, description: "LU: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "LU", year: 2012, description: "La boda del Gran Duque Heredero Guillermo con la Condesa Stéphanie de Lannoy", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2013, description: "LU: Himno Nacional de Luxemburgo, símbolo de identidad." },
  { countryCode: "LU", year: 2014, description: "175 Aniversario de la Fundación de la Independencia de Luxemburgo" },
  { countryCode: "LU", year: 2014, description: "50 aniversario del ascenso al trono del Duque Juan", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "LU", year: 2015, description: "15.º aniversario del acceso al trono de S.A.R. el Gran Duque", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2015, description: "125 aniversario de la Casa de Nassau-Weilburg", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2016, description: "50.º aniversario del \"Puente de la Gran Duquesa Carlota\"" },
  { countryCode: "LU", year: 2017, description: "50.º aniversario de la voluntariedad del ejército luxemburgués" },
  { countryCode: "LU", year: 2017, description: "200.º aniversario del Gran Duque Guillermo III", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2018, description: "150 aniversario de la Constitución de Luxemburgo" },
  { countryCode: "LU", year: 2018, description: "175 aniversario de la muerte del Gran Duque Guillermo I", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2019, description: "100 aniversario de la entronización de la Gran Duquesa Carlota", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2019, description: "100 aniversario del sufragio universal" },
  { countryCode: "LU", year: 2020, description: "200.º aniversario del nacimiento del Príncipe Enrique" },
  { countryCode: "LU", year: 2020, description: "El nacimiento del Príncipe Carlos", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2021, description: "100.º aniversario del Gran Duque Juan", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2021, description: "40.º aniversario del matrimonio del Gran Duque Enrique", seriesName: "Dinastía Gran Ducal" },
  { countryCode: "LU", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "LU", year: 2022, description: "10.º aniversario del matrimonio del Gran Duque Heredero Guillermo" },
  { countryCode: "LU", year: 2022, description: "50 aniversario de la protección legal de la bandera de Luxemburgo" },
  { countryCode: "LU", year: 2023, description: "175 aniversario del Parlamento de Luxemburgo" },
  { countryCode: "LU", year: 2023, description: "25 aniversario de la membresía del Gran Duque Enrique en el COI" },
  { countryCode: "LU", year: 2024, description: "175 aniversario de la muerte del Gran Duque Guillermo II" },
  { countryCode: "LU", year: 2024, description: "100 años de la moneda 'Feierstéppler'" },
  { countryCode: "LU", year: 2025, description: "75 aniversario de la Declaración Schuman" },
  { countryCode: "LU", year: 2025, description: "25 aniversario del acceso del Gran Duque Enrique al trono" },
  { countryCode: "LU", year: 2026, description: "50 aniversario del matrimonio del Príncipe Enrique" },

  // ── LETONIA (LV) ─────────────────────────────────────────────
  { countryCode: "LV", year: 2014, description: "Riga, Capital Europea de la Cultura" },
  { countryCode: "LV", year: 2015, description: "Presidencia letona del Consejo de la Unión Europea" },
  { countryCode: "LV", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "LV", year: 2015, description: "Naturaleza en peligro – la cigüeña negra" },
  { countryCode: "LV", year: 2016, description: "LV: Industria agrícola letona, legado rural." },
  { countryCode: "LV", year: 2016, description: "LV: Vidzeme, región icónica de Letonia." },
  { countryCode: "LV", year: 2017, description: "LV: Curlandia, región histórica de Letonia." },
  { countryCode: "LV", year: 2017, description: "LV: Latgale, región cultural de Letonia." },
  { countryCode: "LV", year: 2018, description: "100 aniversario de los Estados Bálticos" },
  { countryCode: "LV", year: 2018, description: "LV: Zemgale, región agrícola de Letonia." },
  { countryCode: "LV", year: 2019, description: "LV: El sol naciente, símbolo de esperanza." },
  { countryCode: "LV", year: 2020, description: "LV: Cerámica de Latgale, arte tradicional." },
  { countryCode: "LV", year: 2021, description: "100 aniversario del reconocimiento internacional de iure de Letonia" },
  { countryCode: "LV", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "LV", year: 2022, description: "Centenario del Latvijas Banka – educación financiera" },
  { countryCode: "LV", year: 2023, description: "Ucrania – girasol símbolo de paz" },
  { countryCode: "LV", year: 2024, description: "Himmeli – decoración tradicional letona de Navidad" },

  // ── MÓNACO (MC) ──────────────────────────────────────────────
  { countryCode: "MC", year: 2007, description: "25 aniversario de la muerte de la Princesa Grace" },
  { countryCode: "MC", year: 2011, description: "La boda del Príncipe Alberto y Charlene" },
  { countryCode: "MC", year: 2012, description: "500 aniversario de la fundación de la Soberanía de Mónaco, por el fundador Lucien Ier GRIMALDI" },
  { countryCode: "MC", year: 2013, description: "20.º aniversario de la adhesión de Mónaco a la ONU" },
  { countryCode: "MC", year: 2015, description: "800 aniversario de la construcción del primer Castillo sobre la roca" },
  { countryCode: "MC", year: 2016, description: "150 aniversario de la fundación de Montecarlo por Carlos III" },
  { countryCode: "MC", year: 2017, description: "MC: Carabineros del Príncipe, guardia de Mónaco." },
  { countryCode: "MC", year: 2018, description: "MC: François Joseph Bosio, escultor monegasco." },
  { countryCode: "MC", year: 2019, description: "200 aniversario del acceso al trono del Príncipe Honoré V" },
  { countryCode: "MC", year: 2020, description: "Tricentenario del nacimiento del Príncipe Honoré III" },
  { countryCode: "MC", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "MC", year: 2022, description: "100 aniversario de la muerte del Príncipe Alberto I" },
  { countryCode: "MC", year: 2023, description: "100 aniversario del nacimiento del Príncipe Rainiero III" },
  { countryCode: "MC", year: 2024, description: "500 años desde el Tratado con Carlos V" },
  { countryCode: "MC", year: 2025, description: "Marquesado de Baux – feudo histórico" },
  { countryCode: "MC", year: 2025, description: "Condado de Carladès – Título de la familia Grimaldi" },

  // ── MALTA (MT) ───────────────────────────────────────────────
  { countryCode: "MT", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "MT", year: 2011, description: "Historia Constitucional. Primeros representantes electos de 1849" },
  { countryCode: "MT", year: 2012, description: "MT: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "MT", year: 2012, description: "Representación Mayoritaria - 1887" },
  { countryCode: "MT", year: 2013, description: "Establecimiento del Autogobierno en 1921" },
  { countryCode: "MT", year: 2014, description: "MT: Independencia de Malta 1964, hito histórico." },
  { countryCode: "MT", year: 2014, description: "200 aniversario de la Fuerza de Policía de Malta" },
  { countryCode: "MT", year: 2015, description: "Proclamación de la República de Malta en 1974" },
  { countryCode: "MT", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "MT", year: 2015, description: "MT: Primer vuelo desde Malta, avance aéreo." },
  { countryCode: "MT", year: 2016, description: "MT: Templos de Ġgantija, Patrimonio UNESCO." },
  { countryCode: "MT", year: 2017, description: "Templos megalíticos malteses de Hagar Qim" },
  { countryCode: "MT", year: 2017, description: "MT: Solidaridad y paz, valores universales." },
  { countryCode: "MT", year: 2018, description: "MT: Templos de Mnajdra, Patrimonio UNESCO." },
  { countryCode: "MT", year: 2018, description: "MT: Patrimonio Cultural de Malta, legado histórico." },
  { countryCode: "MT", year: 2019, description: "Templos prehistóricos de Ta’ Haġrat" },
  { countryCode: "MT", year: 2019, description: "MT: Naturaleza y Medio Ambiente, conciencia ecológica." },
  { countryCode: "MT", year: 2020, description: "Templos prehistóricos de Skorba" },
  { countryCode: "MT", year: 2020, description: "MT: Juegos infantiles, alegría y tradición." },
  { countryCode: "MT", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "MT", year: 2022, description: "Mujeres, Paz y Seguridad – Resolución 1325 de la ONU" },
  { countryCode: "MT", year: 2022, description: "Hipogeo de Ħal Saflieni – Patrimonio de la Humanidad de la UNESCO", seriesName: "Patrimonio de la Humanidad UNESCO" },
  { countryCode: "MT", year: 2023, description: "225 aniversario de la llegada de los franceses a Malta" },
  { countryCode: "MT", year: 2023, description: "550 aniversario del nacimiento de Nicolaus Copernicus" },
  { countryCode: "MT", year: 2024, description: "Abeja melífera maltesa – especie endémica" },
  { countryCode: "MT", year: 2024, description: "La Ciudadela de la isla de Gozo" },
  { countryCode: "MT", year: 2025, description: "Ciudad de Mdina – serie de ciudades amuralladas maltesas" },
  { countryCode: "MT", year: 2025, description: "Toro maltés – raza autóctona en peligro de extinción" },

  // ── PAÍSES BAJOS (NL) ────────────────────────────────────────
  { countryCode: "NL", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "NL", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "NL", year: 2011, description: "500.º aniversario de la publicación del mundialmente famoso libro ‘Elogio de la locura’ del filósofo, humanista y teólogo neerlandés Erasmo de Róterdam" },
  { countryCode: "NL", year: 2012, description: "NL: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "NL", year: 2013, description: "NL: Anuncio de Cambio de Trono, sucesión real." },
  { countryCode: "NL", year: 2013, description: "200 Aniversario del Reino de los Países Bajos" },
  { countryCode: "NL", year: 2014, description: "NL: Cambio de Trono, nueva era monárquica." },
  { countryCode: "NL", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "NL", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },

  // ── PORTUGAL (PT) ────────────────────────────────────────────
  { countryCode: "PT", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "PT", year: 2007, description: "Presidencia Portuguesa del Consejo de la Unión Europea" },
  { countryCode: "PT", year: 2008, description: "60 aniversario de la Declaración Universal de Derechos Humanos" },
  { countryCode: "PT", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "PT", year: 2009, description: "PT: 2º Juegos de la Lusofonía, unión cultural." },
  { countryCode: "PT", year: 2010, description: "100 aniversario de la República Portuguesa" },
  { countryCode: "PT", year: 2011, description: "500 aniversario del nacimiento de Fernão Mendes Pinto" },
  { countryCode: "PT", year: 2012, description: "PT: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "PT", year: 2012, description: "Guimarães, Capital Europea de la Cultura 2012, en el Norte de Portugal" },
  { countryCode: "PT", year: 2013, description: "250 Aniversario de la Torre de los Clérigos" },
  { countryCode: "PT", year: 2014, description: "40 aniversario de la Revolución de los Claveles" },
  { countryCode: "PT", year: 2014, description: "Año Internacional de la Agricultura Familiar" },
  { countryCode: "PT", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "PT", year: 2015, description: "150 aniversario de la Cruz Roja Portuguesa" },
  { countryCode: "PT", year: 2015, description: "500 años de los primeros contactos con Timor, hoy país independiente de habla portuguesa" },
  { countryCode: "PT", year: 2016, description: "Equipo portugués participante en los Juegos Olímpicos de Río 2016" },
  { countryCode: "PT", year: 2016, description: "50 años del primer puente que unió ambas orillas del río Tajo" },
  { countryCode: "PT", year: 2017, description: "PT: 150 Años de Seguridad Pública, servicio al país." },
  { countryCode: "PT", year: 2017, description: "150 años del nacimiento del escritor Raúl Brandão" },
  { countryCode: "PT", year: 2018, description: "250 años de la Imprenta Oficial" },
  { countryCode: "PT", year: 2018, description: "250 años del Jardín Botánico de Ajuda" },
  { countryCode: "PT", year: 2019, description: "500 años de la primera circunnavegación organizada y liderada por el explorador y navegante portugués Fernão De Magalhães" },
  { countryCode: "PT", year: 2019, description: "600 años del descubrimiento del Archipiélago de Madeira, por los navegantes portugueses Bartolomeu Perestrelo y Tristão Vaz" },
  { countryCode: "PT", year: 2020, description: "730 aniversario de la Universidad de Coimbra" },
  { countryCode: "PT", year: 2020, description: "75 aniversario de las Naciones Unidas" },
  { countryCode: "PT", year: 2021, description: "Presidencia Portuguesa del Consejo de la Unión Europea" },
  { countryCode: "PT", year: 2021, description: "Participación de Portugal en los Juegos Olímpicos de Tokio 2020" },
  { countryCode: "PT", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "PT", year: 2022, description: "100 aniversario del primer cruce aéreo del Atlántico Sur (Coutinho y Cabral)" },
  { countryCode: "PT", year: 2023, description: "Jornada Mundial de la Juventud – Lisboa 2023" },
  { countryCode: "PT", year: 2023, description: "PT: Paz entre las naciones, anhelo global." },
  { countryCode: "PT", year: 2024, description: "50 aniversario de la Revolución de los Claveles (25 de abril de 1974)" },
  { countryCode: "PT", year: 2024, description: "Portugal en los Juegos Olímpicos de París 2024" },
  { countryCode: "PT", year: 2025, description: "Desarrollo sostenible – Agenda 2030 de la ONU" },
  { countryCode: "PT", year: 2025, description: "Escultismo Mundial – 16º Moot Scout Mundial en Portugal" },

  // ── ESLOVENIA (SI) ───────────────────────────────────────────
  { countryCode: "SI", year: 2007, description: "50.º aniversario de la firma del Tratado de Roma", seriesName: "50 años de Europa", isCommonIssue: true },
  { countryCode: "SI", year: 2008, description: "500.º aniversario del nacimiento de Primož Trubar" },
  { countryCode: "SI", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "SI", year: 2010, description: "SI: Jardín Botánico de Liubliana, naturaleza eslovena." },
  { countryCode: "SI", year: 2011, description: "100 aniversario del nacimiento del héroe nacional Franc Rozman-Stane" },
  { countryCode: "SI", year: 2012, description: "SI: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "SI", year: 2013, description: "800 Aniversario de la primera visita a la Postojna jama" },
  { countryCode: "SI", year: 2014, description: "600.º aniversario de la Coronación de Bárbara de Celje" },
  { countryCode: "SI", year: 2015, description: "2000 aniversario de la Fundación de Emona" },
  { countryCode: "SI", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "SI", year: 2016, description: "25 aniversario de la independencia de la República de Eslovenia" },
  { countryCode: "SI", year: 2017, description: "10 aniversario del euro en Eslovenia" },
  { countryCode: "SI", year: 2018, description: "Día Mundial de las Abejas de Eslovenia" },
  { countryCode: "SI", year: 2019, description: "100 aniversario de la fundación de la Universidad de Liubliana" },
  { countryCode: "SI", year: 2020, description: "500 aniversario del nacimiento de Adam Bohorič" },
  { countryCode: "SI", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "SI", year: 2022, description: "150 aniversario del nacimiento del arquitecto Jože Plečnik" },
  { countryCode: "SI", year: 2023, description: "150 aniversario del nacimiento del matemático Josip Plemelj" },
  { countryCode: "SI", year: 2024, description: "250 años de la Biblioteca Nacional y Universitaria" },
  { countryCode: "SI", year: 2025, description: "100 aniversario del nacimiento de Miki Muster" },

  // ── ESLOVAQUIA (SK) ──────────────────────────────────────────
  { countryCode: "SK", year: 2009, description: "Diez años de unión económica y monetaria (UEM) y el nacimiento del euro", seriesName: "10 años de la UEM", isCommonIssue: true },
  { countryCode: "SK", year: 2009, description: "20 aniversario del \"Día de la lucha por la libertad y la democracia\"" },
  { countryCode: "SK", year: 2011, description: "20 aniversario de la formación del Grupo de Visegrado" },
  { countryCode: "SK", year: 2012, description: "SK: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "SK", year: 2013, description: "1150 aniversario de la llegada bizantina de San Cirilo y San Metodio a la Gran Moravia" },
  { countryCode: "SK", year: 2014, description: "10 aniversario de la adhesión de Eslovaquia a la Unión Europea" },
  { countryCode: "SK", year: 2015, description: "30 aniversario de la bandera de la Unión Europea", seriesName: "30 aniversario de la bandera de la UE", isCommonIssue: true },
  { countryCode: "SK", year: 2015, description: "200.º aniversario del nacimiento de Ľudovít Štúr" },
  { countryCode: "SK", year: 2016, description: "La primera Presidencia eslovaca del Consejo de la Unión Europea" },
  { countryCode: "SK", year: 2017, description: "550 aniversario de la Universidad Istropolitana" },
  { countryCode: "SK", year: 2018, description: "25.º aniversario de la creación de la República Eslovaca" },
  { countryCode: "SK", year: 2019, description: "100.º aniversario de la muerte de Milan Rastislav Štefánik" },
  { countryCode: "SK", year: 2020, description: "20 aniversario de la adhesión de Eslovaquia a la Organización para la Cooperación y el Desarrollo Económicos (OCDE)" },
  { countryCode: "SK", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "SK", year: 2022, description: "300 aniversario de la primera máquina de vapor de Europa" },
  { countryCode: "SK", year: 2023, description: "200.º aniversario del servicio de correo expreso en diligencia Viena–Bratislava" },
  { countryCode: "SK", year: 2023, description: "100.º aniversario de la primera transfusión de sangre en Eslovaquia" },
  { countryCode: "SK", year: 2024, description: "100 aniversario de la Maratón de la Paz de Košice" },
  { countryCode: "SK", year: 2025, description: "100.º aniversario del Campeonato de Europa de Hockey sobre Hielo (1925)" },

  // ── SAN MARINO (SM) ──────────────────────────────────────────
  { countryCode: "SM", year: 2004, description: "SM: Bartolomeo Borghesi, numismático italiano." },
  { countryCode: "SM", year: 2005, description: "SM: Año Mundial de la Física 2005, ciencia." },
  { countryCode: "SM", year: 2006, description: "V centenario de la muerte de Cristóbal Colón" },
  { countryCode: "SM", year: 2007, description: "Bicentenario del nacimiento de Giuseppe Garibaldi" },
  { countryCode: "SM", year: 2008, description: "Año Europeo del Diálogo Intercultural" },
  { countryCode: "SM", year: 2009, description: "Año Europeo de la Creatividad y la Innovación" },
  { countryCode: "SM", year: 2010, description: "500 aniversario de la muerte de Sandro Botticelli" },
  { countryCode: "SM", year: 2011, description: "500 aniversario del nacimiento de Giorgio Vasari" },
  { countryCode: "SM", year: 2012, description: "SM: 10 años del Euro, símbolo de unión.", seriesName: "10 años de billetes y monedas euro", isCommonIssue: true },
  { countryCode: "SM", year: 2013, description: "Quinto centenario de la muerte de Il Pinturicchio" },
  { countryCode: "SM", year: 2014, description: "500 aniversario de la muerte de Donato Bramante" },
  { countryCode: "SM", year: 2014, description: "90 aniversario de la muerte de Giacomo Puccini" },
  { countryCode: "SM", year: 2015, description: "750 aniversario del nacimiento de Dante Alighieri" },
  { countryCode: "SM", year: 2015, description: "25 aniversario de la reunificación alemana" },
  { countryCode: "SM", year: 2016, description: "550 aniversario de la muerte de Donatello" },
  { countryCode: "SM", year: 2016, description: "400 aniversario de la muerte de William Shakespeare" },
  { countryCode: "SM", year: 2017, description: "750 aniversario del nacimiento de Giotto" },
  { countryCode: "SM", year: 2017, description: "Año Internacional del Turismo Sostenible para el Desarrollo" },
  { countryCode: "SM", year: 2018, description: "500 aniversario del nacimiento de Tintoretto" },
  { countryCode: "SM", year: 2018, description: "420 aniversario del nacimiento de Gian Lorenzo Bernini" },
  { countryCode: "SM", year: 2019, description: "500.º aniversario de la muerte de Leonardo da Vinci" },
  { countryCode: "SM", year: 2019, description: "550.º aniversario de la muerte de Filippo Lippi" },
  { countryCode: "SM", year: 2020, description: "Quinto centenario de la muerte de Rafael" },
  { countryCode: "SM", year: 2020, description: "250 aniversario de la muerte de Giambattista Tiepolo" },
  { countryCode: "SM", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "SM", year: 2022, description: "530 aniversario de la muerte de Piero della Francesca" },
  { countryCode: "SM", year: 2022, description: "Bicentenario de la muerte de Antonio Canova" },
  { countryCode: "SM", year: 2023, description: "500.º aniversario de la muerte de Luca Signorelli" },
  { countryCode: "SM", year: 2024, description: "530 aniversario de la muerte de Ghirlandaio" },
  { countryCode: "SM", year: 2024, description: "50 aniversario de la Declaración de Derechos Ciudadanos" },
  { countryCode: "SM", year: 2025, description: "Año Jubilar 2025 – Peregrinos de la Esperanza" },

  // ── VATICANO (VA) ────────────────────────────────────────────
  { countryCode: "VA", year: 2004, description: "75.º aniversario de la fundación del Estado de la Ciudad del Vaticano" },
  { countryCode: "VA", year: 2005, description: "XX Jornada Mundial de la Juventud celebrada en Colonia en agosto de 2005" },
  { countryCode: "VA", year: 2006, description: "V centenario de la Guardia Suiza Pontificia" },
  { countryCode: "VA", year: 2007, description: "80 cumpleaños de Su Santidad Benedicto XVI" },
  { countryCode: "VA", year: 2008, description: "VA: 2008, Año de San Pablo, figura religiosa." },
  { countryCode: "VA", year: 2009, description: "Año Internacional de la Astronomía" },
  { countryCode: "VA", year: 2010, description: "VA: Año Sacerdotal, homenaje al clero." },
  { countryCode: "VA", year: 2011, description: "26.ª Jornada Mundial de la Juventud" },
  { countryCode: "VA", year: 2012, description: "7º Encuentro Mundial de las Familias" },
  { countryCode: "VA", year: 2013, description: "VA: Sede vacante, periodo interino papal." },
  { countryCode: "VA", year: 2013, description: "28ª Jornada Mundial de la Juventud - Río de Janeiro" },
  { countryCode: "VA", year: 2014, description: "25 aniversario de la caída del Muro de Berlín" },
  { countryCode: "VA", year: 2015, description: "El VIII Encuentro Mundial de las Familias" },
  { countryCode: "VA", year: 2016, description: "200 aniversario de la Guardia Vaticana" },
  { countryCode: "VA", year: 2016, description: "VA: Jubileo de la Misericordia, evento religioso." },
  { countryCode: "VA", year: 2017, description: "1950 aniversario del martirio de San Pedro y San Pablo" },
  { countryCode: "VA", year: 2017, description: "Centenario de las apariciones de Fátima" },
  { countryCode: "VA", year: 2018, description: "VA: El grupo del Laocoonte, arte clásico." },
  { countryCode: "VA", year: 2018, description: "50 Aniversario de la muerte del Padre Pío" },
  { countryCode: "VA", year: 2019, description: "90 aniversario de la fundación del Estado de la Ciudad del Vaticano" },
  { countryCode: "VA", year: 2019, description: "Capilla Sixtina – Fin de la restauración 1994-2019" },
  { countryCode: "VA", year: 2020, description: "100 aniversario del nacimiento del Papa Juan Pablo II" },
  { countryCode: "VA", year: 2020, description: "500 aniversario de la muerte de Rafael Sanzio" },
  { countryCode: "VA", year: 2022, description: "35.º aniversario del programa Erasmus", seriesName: "35 años del programa Erasmus", isCommonIssue: true },
  { countryCode: "VA", year: 2022, description: "25.º aniversario de la muerte de la Madre Teresa de Calcuta" },
  { countryCode: "VA", year: 2022, description: "125.º aniversario del nacimiento del Papa Pablo VI" },
  { countryCode: "VA", year: 2023, description: "150.º aniversario de la muerte de Alessandro Manzoni" },
  { countryCode: "VA", year: 2023, description: "500 aniversario de la muerte de Pietro Perugino" },
  { countryCode: "VA", year: 2024, description: "750.º aniversario de la muerte de Santo Tomás de Aquino" },
  { countryCode: "VA", year: 2024, description: "150.º aniversario del nacimiento de Guglielmo Marconi" },
  { countryCode: "VA", year: 2025, description: "550 aniversario del nacimiento de Miguel Ángel" },
  { countryCode: "VA", year: 2025, description: "Jubileo 2025 – apertura de la Puerta Santa" },
  { countryCode: "VA", year: 2025, description: "VA: Sede Vacante 2025, periodo interino papal." },
];
